// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for user (user@user-multicom) on Fri Sep 25 13:42:36 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "CharstringOutputPortType.hh"

namespace CoffeeSuite {

CharstringOutputPortType::CharstringOutputPortType(const char *par_port_name)
	: CharstringOutputPortType_BASE(par_port_name)
{

}

CharstringOutputPortType::~CharstringOutputPortType()
{

}

void CharstringOutputPortType::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void CharstringOutputPortType::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void CharstringOutputPortType::Handle_Fd_Event_Error(int /*fd*/)
{

}

void CharstringOutputPortType::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void CharstringOutputPortType::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void CharstringOutputPortType::Handle_Timeout(double time_since_last_call) {}*/

void CharstringOutputPortType::user_map(const char * /*system_port*/)
{

}

void CharstringOutputPortType::user_unmap(const char * /*system_port*/)
{

}

void CharstringOutputPortType::user_start()
{

}

void CharstringOutputPortType::user_stop()
{

}

void CharstringOutputPortType::outgoing_send(const CHARSTRING& /*send_par*/)
{

}

} /* end of namespace */

