// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for user (user@user-multicom) on Fri Sep 25 13:42:36 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "IntegerInputPortType.hh"

namespace CoffeeSuite {

IntegerInputPortType::IntegerInputPortType(const char *par_port_name)
	: IntegerInputPortType_BASE(par_port_name)
{

}

IntegerInputPortType::~IntegerInputPortType()
{

}

void IntegerInputPortType::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void IntegerInputPortType::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void IntegerInputPortType::Handle_Fd_Event_Error(int /*fd*/)
{

}

void IntegerInputPortType::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void IntegerInputPortType::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void IntegerInputPortType::Handle_Timeout(double time_since_last_call) {}*/

void IntegerInputPortType::user_map(const char * /*system_port*/)
{

}

void IntegerInputPortType::user_unmap(const char * /*system_port*/)
{

}

void IntegerInputPortType::user_start()
{

}

void IntegerInputPortType::user_stop()
{

}

} /* end of namespace */

