// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for user (user@user-multicom) on Fri Oct  9 11:34:10 2015

// Copyright Ericsson Telecom AB 2000-2014

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "jabber_iq_auth.hh"

namespace jabber__iq__auth {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const unsigned char module_checksum[] = { 0x23, 0xae, 0x8d, 0x99, 0x30, 0x4b, 0xb4, 0x94, 0x97, 0xdd, 0xdd, 0xf0, 0x99, 0x4a, 0xe8, 0x90 };

/* Global variable definitions */

const XERdescriptor_t       Query_choice_xer_ = { {"choice>\n", "choice>\n"}, {8, 8}, 0 |UNTAGGED, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_JSONdescriptor_t Query_choice_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Query_choice_descr_ = { "@jabber_iq_auth.Query.choice", NULL, NULL, NULL, &Query_choice_xer_, &Query_choice_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_choice_password__list_xer_ = { {"password_list>\n", "password_list>\n"}, {15, 15}, 0 |UNTAGGED, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, &Query_choice_password__list_0_xer_ };
const TTCN_JSONdescriptor_t Query_choice_password__list_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Query_choice_password__list_descr_ = { "@jabber_iq_auth.Query.choice.password_list", NULL, NULL, NULL, &Query_choice_password__list_xer_, &Query_choice_password__list_json_, &Query_choice_password__list_0_descr_, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_choice_password__list_0_xer_ = { {"String>\n", "password>\n"}, {8, 10}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Query_choice_password__list_0_descr_ = { "@jabber_iq_auth.Query.choice.password_list.<oftype>", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Query_choice_password__list_0_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_choice_digest__list_xer_ = { {"digest_list>\n", "digest_list>\n"}, {13, 13}, 0 |UNTAGGED, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, &Query_choice_digest__list_0_xer_ };
const TTCN_JSONdescriptor_t Query_choice_digest__list_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Query_choice_digest__list_descr_ = { "@jabber_iq_auth.Query.choice.digest_list", NULL, NULL, NULL, &Query_choice_digest__list_xer_, &Query_choice_digest__list_json_, &Query_choice_digest__list_0_descr_, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_choice_digest__list_0_xer_ = { {"String>\n", "digest>\n"}, {8, 8}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Query_choice_digest__list_0_descr_ = { "@jabber_iq_auth.Query.choice.digest_list.<oftype>", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Query_choice_digest__list_0_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_xer_ = { {"Query>\n", "query>\n"}, {7, 7}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_JSONdescriptor_t Query_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Query_descr_ = { "@jabber_iq_auth.Query", NULL, NULL, NULL, &Query_xer_, &Query_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_username_xer_ = { {"username>\n", "username>\n"}, {10, 10}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Query_username_descr_ = { "@jabber_iq_auth.Query.username", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Query_username_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Query_resource_xer_ = { {"resource>\n", "resource>\n"}, {10, 10}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Query_resource_descr_ = { "@jabber_iq_auth.Query.resource", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Query_resource_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
static const size_t num_namespaces = 21;
static const namespace_t xml_namespaces[num_namespaces+1] = {
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { "jabber:iq:auth", "tq0011" },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { "http://www.w3.org/2001/XMLSchema-instance", "xsi" }
};

TTCN_Module module_object("jabber_iq_auth", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 21LU, xml_namespaces, post_init_module, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_5,
  current_runtime_version.requires_minor_version_3,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Member functions of C++ classes */

void Query_choice::copy_value(const Query_choice& other_value)
{
switch (other_value.union_selection) {
case ALT_password__list:
field_password__list = new Query_choice_password__list(*other_value.field_password__list);
break;
case ALT_digest__list:
field_digest__list = new Query_choice_digest__list(*other_value.field_digest__list);
break;
default:
TTCN_error("Assignment of an unbound union value of type @jabber_iq_auth.Query.choice.");
}
union_selection = other_value.union_selection;
}

Query_choice::Query_choice()
{
union_selection = UNBOUND_VALUE;
}

Query_choice::Query_choice(const Query_choice& other_value)
: Base_Type(){
copy_value(other_value);
}

Query_choice::~Query_choice()
{
clean_up();
}

Query_choice& Query_choice::operator=(const Query_choice& other_value)
{
if (this != &other_value) {
clean_up();
copy_value(other_value);
}
return *this;
}

boolean Query_choice::operator==(const Query_choice& other_value) const
{
if (union_selection == UNBOUND_VALUE) TTCN_error("The left operand of comparison is an unbound value of union type @jabber_iq_auth.Query.choice.");
if (other_value.union_selection == UNBOUND_VALUE) TTCN_error("The right operand of comparison is an unbound value of union type @jabber_iq_auth.Query.choice.");
if (union_selection != other_value.union_selection) return FALSE;
switch (union_selection) {
case ALT_password__list:
return *field_password__list == *other_value.field_password__list;
case ALT_digest__list:
return *field_digest__list == *other_value.field_digest__list;
default:
return FALSE;
}
}

Query_choice_password__list& Query_choice::password__list()
{
if (union_selection != ALT_password__list) {
clean_up();
field_password__list = new Query_choice_password__list;
union_selection = ALT_password__list;
}
return *field_password__list;
}

const Query_choice_password__list& Query_choice::password__list() const
{
if (union_selection != ALT_password__list) TTCN_error("Using non-selected field password_list in a value of union type @jabber_iq_auth.Query.choice.");
return *field_password__list;
}

Query_choice_digest__list& Query_choice::digest__list()
{
if (union_selection != ALT_digest__list) {
clean_up();
field_digest__list = new Query_choice_digest__list;
union_selection = ALT_digest__list;
}
return *field_digest__list;
}

const Query_choice_digest__list& Query_choice::digest__list() const
{
if (union_selection != ALT_digest__list) TTCN_error("Using non-selected field digest_list in a value of union type @jabber_iq_auth.Query.choice.");
return *field_digest__list;
}

boolean Query_choice::ischosen(union_selection_type checked_selection) const
{
if (checked_selection == UNBOUND_VALUE) TTCN_error("Internal error: Performing ischosen() operation on an invalid field of union type @jabber_iq_auth.Query.choice.");
if (union_selection == UNBOUND_VALUE) TTCN_error("Performing ischosen() operation on an unbound value of union type @jabber_iq_auth.Query.choice.");
return union_selection == checked_selection;
}

boolean Query_choice::is_bound() const
{
  return union_selection != UNBOUND_VALUE;
}

boolean Query_choice::is_value() const
{
switch (union_selection) {
case UNBOUND_VALUE: return FALSE;
case ALT_password__list: return field_password__list->is_value();
case ALT_digest__list: return field_digest__list->is_value();
default: TTCN_error("Invalid selection in union is_bound");}
}

void Query_choice::clean_up()
{
switch (union_selection) {
case ALT_password__list:
  delete field_password__list;
  break;
case ALT_digest__list:
  delete field_digest__list;
  break;
default:
  break;
}
union_selection = UNBOUND_VALUE;
}

void Query_choice::log() const
{
switch (union_selection) {
case ALT_password__list:
TTCN_Logger::log_event_str("{ password_list := ");
field_password__list->log();
TTCN_Logger::log_event_str(" }");
break;
case ALT_digest__list:
TTCN_Logger::log_event_str("{ digest_list := ");
field_digest__list->log();
TTCN_Logger::log_event_str(" }");
break;
default:
TTCN_Logger::log_event_unbound();
}
}

void Query_choice::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for union type `@jabber_iq_auth.Query.choice'");
    }
    if (strcmp("password_list", param_field) == 0) {
      password__list().set_param(param);
      return;
    } else if (strcmp("digest_list", param_field) == 0) {
      digest__list().set_param(param);
      return;
    } else param.error("Field `%s' not found in union type `@jabber_iq_auth.Query.choice'", param_field);
  }
  param.basic_check(Module_Param::BC_VALUE, "union value");
  if (param.get_type()==Module_Param::MP_Value_List && param.get_size()==0) return;
  if (param.get_type()!=Module_Param::MP_Assignment_List) {
    param.error("union value with field name was expected");
  }
  Module_Param* mp_last = param.get_elem(param.get_size()-1);
  if (!strcmp(mp_last->get_id()->get_name(), "password_list")) {
    password__list().set_param(*mp_last);
    return;
  }
  if (!strcmp(mp_last->get_id()->get_name(), "digest_list")) {
    digest__list().set_param(*mp_last);
    return;
  }
  mp_last->error("Field %s does not exist in type @jabber_iq_auth.Query.choice.", mp_last->get_id()->get_name());
}

void Query_choice::set_implicit_omit()
{
switch (union_selection) {
case ALT_password__list:
field_password__list->set_implicit_omit(); break;
case ALT_digest__list:
field_digest__list->set_implicit_omit(); break;
default: break;
}
}

void Query_choice::encode_text(Text_Buf& text_buf) const
{
text_buf.push_int(union_selection);
switch (union_selection) {
case ALT_password__list:
field_password__list->encode_text(text_buf);
break;
case ALT_digest__list:
field_digest__list->encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an unbound value of union type @jabber_iq_auth.Query.choice.");
}
}

void Query_choice::decode_text(Text_Buf& text_buf)
{
switch ((union_selection_type)text_buf.pull_int().get_val()) {
case ALT_password__list:
password__list().decode_text(text_buf);
break;
case ALT_digest__list:
digest__list().decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized union selector was received for type @jabber_iq_auth.Query.choice.");
}
}

void Query_choice::encode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...) const
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-encoding type '%s': ", p_td.name);
    unsigned BER_coding=va_arg(pvar, unsigned);
    BER_encode_chk_coding(BER_coding);
    ASN_BER_TLV_t *tlv=BER_encode_TLV(p_td, BER_coding);
    tlv->put_in_buffer(p_buf);
    ASN_BER_TLV_t::destruct(tlv);
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-encoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    RAW_enc_tr_pos rp;
    rp.level=0;
    rp.pos=NULL;
    RAW_enc_tree root(TRUE, NULL, &rp, 1, p_td.raw);
    RAW_encode(p_td, root);
    root.put_to_buf(p_buf);
    break;}
  case TTCN_EncDec::CT_TEXT: {
    TTCN_EncDec_ErrorContext ec("While TEXT-encoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
      ("No TEXT descriptor available for type '%s'.", p_td.name);
    TEXT_encode(p_td,p_buf);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-encoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XER_encode(*(p_td.xer),p_buf, XER_coding, 0, 0);
    p_buf.put_c('\n');
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-encoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok(va_arg(pvar, int) != 0);
    JSON_encode(p_td, tok);
    p_buf.put_s(tok.get_buffer_length(), (const unsigned char*)tok.get_buffer());
    break;}
  default:
    TTCN_error("Unknown coding method requested to encode type '%s'", p_td.name);
  }
  va_end(pvar);
}

void Query_choice::decode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...)
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-decoding type '%s': ", p_td.name);
    unsigned L_form=va_arg(pvar, unsigned);
    ASN_BER_TLV_t tlv;
    BER_decode_str2TLV(p_buf, tlv, L_form);
    BER_decode_TLV(p_td, tlv, L_form);
    if(tlv.isComplete) p_buf.increase_pos(tlv.get_len());
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-decoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    raw_order_t r_order;
    switch(p_td.raw->top_bit_order) {
    case TOP_BIT_LEFT:
      r_order=ORDER_LSB;
      break;
    case TOP_BIT_RIGHT:
    default:
      r_order=ORDER_MSB;
    }
    int rawr = RAW_decode(p_td, p_buf, p_buf.get_len()*8, r_order);
    if(rawr<0) switch (-rawr) {
    case TTCN_EncDec::ET_INCOMPL_MSG:
    case TTCN_EncDec::ET_LEN_ERR:
      ec.error((TTCN_EncDec::error_type_t)-rawr, "Can not decode type '%s', because incomplete message was received", p_td.name);
      break;
    case 1:
    default:
      ec.error(TTCN_EncDec::ET_INVAL_MSG, "Can not decode type '%s', because invalid message was received", p_td.name);
      break;
    }
    break;}
  case TTCN_EncDec::CT_TEXT: {
    Limit_Token_List limit;
    TTCN_EncDec_ErrorContext ec("While TEXT-decoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
        ("No TEXT descriptor available for type '%s'.", p_td.name);
    const unsigned char *b_data=p_buf.get_data();
    if(b_data[p_buf.get_len()-1]!='\0'){
      p_buf.set_pos(p_buf.get_len());
      p_buf.put_zero(8,ORDER_LSB);
      p_buf.rewind();
    }
    if(TEXT_decode(p_td,p_buf,limit)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-decoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XmlReaderWrap reader(p_buf);
    for (int rd_ok=reader.Read(); rd_ok==1; rd_ok=reader.Read()) {
      if (reader.NodeType() == XML_READER_TYPE_ELEMENT) break;
    }
    XER_decode(*(p_td.xer), reader, XER_coding | XER_TOPLEVEL, 0);
    size_t bytes = reader.ByteConsumed();
    p_buf.set_pos(bytes);
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-decoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok((const char*)p_buf.get_data(), p_buf.get_len());
    if(JSON_decode(p_td, tok, false)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    p_buf.set_pos(tok.get_buf_pos());
    break;}
  default:
    TTCN_error("Unknown coding method requested to decode type '%s'", p_td.name);
  }
  va_end(pvar);
}

boolean Query_choice::can_start(const char *name, const char *uri, const XERdescriptor_t& xd, unsigned int flavor) {
  boolean exer = is_exer(flavor);
  if (!exer || (!(xd.xer_bits & UNTAGGED) && !(flavor & (USE_NIL|(exer ? XER_LIST : XER_RECOF))))) return check_name(name, xd, exer) && (!exer || (flavor & USE_TYPE_ATTR) || check_namespace(uri, xd));
  flavor &= ~XER_RECOF;
  if (Query_choice_password__list::can_start(name, uri, Query_choice_password__list_xer_, flavor)) return true;
  if (Query_choice_digest__list::can_start(name, uri, Query_choice_digest__list_xer_, flavor)) return true;
  return false;
}

char ** Query_choice::collect_ns(const XERdescriptor_t& p_td, size_t& num, bool& def_ns) const {
  size_t num_collected;
  char **collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
  char **new_ns;
  size_t num_new;
  boolean need_type = FALSE;
  try {
    bool def_ns_1 = false;
    switch (union_selection) {
    case ALT_password__list:
      new_ns = field_password__list->collect_ns(Query_choice_password__list_xer_, num_new, def_ns_1);
      def_ns = def_ns || def_ns_1;
      merge_ns(collected_ns, num_collected, new_ns, num_new);
      break;
    case ALT_digest__list:
      new_ns = field_digest__list->collect_ns(Query_choice_digest__list_xer_, num_new, def_ns_1);
      def_ns = def_ns || def_ns_1;
      merge_ns(collected_ns, num_collected, new_ns, num_new);
      need_type = (Query_choice_digest__list_xer_.namelens[1] > 2);
      break;
    default: break;
    }
    if ((p_td.xer_bits & USE_TYPE_ATTR) && !(p_td.xer_bits & XER_ATTRIBUTE) && need_type) {
      collected_ns = (char**)Realloc(collected_ns, sizeof(char*) * ++num_collected);
      const namespace_t *c_ns = p_td.my_module->get_controlns();
      collected_ns[num_collected-1] = mprintf(" xmlns:%s='%s'", c_ns->px, c_ns->ns);
    }
  }
  catch (...) {
    while (num_collected > 0) Free(collected_ns[--num_collected]);
    Free(collected_ns);
    throw;
  }
  num = num_collected;
  return collected_ns;
}

int Query_choice::XER_encode(const XERdescriptor_t& p_td, TTCN_Buffer& p_buf, unsigned int p_flavor, int p_indent, embed_values_enc_struct_t*) const
{
  if (UNBOUND_VALUE==union_selection) {
    TTCN_error("Attempt to XER-encode an unbound union value.");
    return 0;
  }
  TTCN_EncDec_ErrorContext ec_0("Alternative '");
  TTCN_EncDec_ErrorContext ec_1;
  int encoded_length=(int)p_buf.get_len();
  unsigned int flavor_1 = p_flavor;
  if (is_exer(p_flavor)) flavor_1 &= ~XER_RECOF;
  bool omit_tag = begin_xml(p_td, p_buf, flavor_1, p_indent, false, (collector_fn)&Query_choice::collect_ns);
  unsigned int flavor_0 = (p_flavor & XER_MASK);
  switch (union_selection) {
  case ALT_password__list:
    ec_1.set_msg("password_list': ");
    field_password__list->XER_encode(Query_choice_password__list_xer_, p_buf, flavor_0, p_indent + (!p_indent || !omit_tag), 0);
    break;
  case ALT_digest__list:
    ec_1.set_msg("digest_list': ");
    field_digest__list->XER_encode(Query_choice_digest__list_xer_, p_buf, flavor_0, p_indent + (!p_indent || !omit_tag), 0);
    break;
  case UNBOUND_VALUE:
    (void)flavor_0;
    break;
  } //switch
  end_xml(p_td, p_buf, flavor_1, p_indent, 0);
  return (int)p_buf.get_len() - encoded_length;
}

int Query_choice::XER_decode(const XERdescriptor_t& p_td, XmlReaderWrap& p_reader, unsigned int p_flavor, embed_values_dec_struct_t*)
{
  int e_xer = is_exer(p_flavor);
  int type = 0;
  int rd_ok=1, xml_depth=-1;
  int xerbits = p_td.xer_bits;
  if (p_flavor & XER_TOPLEVEL) xerbits &= ~UNTAGGED;
  if (xerbits & USE_TYPE_ATTR) p_flavor &= ~XER_RECOF;
  boolean own_tag = !(e_xer && ((xerbits & (ANY_ELEMENT | UNTAGGED)) || (p_flavor & (USE_NIL|(e_xer ? XER_LIST : XER_RECOF)))));
  if ((e_xer || !is_record_of(p_flavor)) && own_tag)
  for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_ELEMENT) {
      verify_name(p_reader, p_td, e_xer);
      xml_depth = p_reader.Depth();
      if (!(e_xer && (p_td.xer_bits & USE_TYPE_ATTR))
        && !p_reader.IsEmptyElement()) rd_ok = p_reader.Read();
      break;
    }
  }
  unsigned int flavor_1 = (p_flavor & XER_MASK);
  for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_ELEMENT) break;
    else if (type == XML_READER_TYPE_END_ELEMENT) break;
  }
  if (rd_ok) {
    TTCN_EncDec_ErrorContext ec_1("Alternative '");
    TTCN_EncDec_ErrorContext ec_2;
    const char *elem_name;
    const char *ns_uri = 0;
    {
      elem_name = (const char*)p_reader.LocalName();
      ns_uri    = (const char*)p_reader.NamespaceUri();
    }
    if (type!=XML_READER_TYPE_ELEMENT || (own_tag && p_reader.IsEmptyElement())) goto empty_xml;
    if (Query_choice_digest__list::can_start(elem_name, ns_uri, Query_choice_digest__list_xer_, flavor_1) || (Query_choice_digest__list_xer_.xer_bits & ANY_ELEMENT)) {
      ec_2.set_msg("digest_list': ");
      digest__list().XER_decode(Query_choice_digest__list_xer_, p_reader, flavor_1, 0);
      if (!digest__list().is_bound()) {
        TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "Failed to decode field.");
      }
    }
    else if ((e_xer && (type==XML_READER_TYPE_END_ELEMENT || !own_tag)) || Query_choice_password__list::can_start(elem_name, ns_uri, Query_choice_password__list_xer_, flavor_1) || (Query_choice_password__list_xer_.xer_bits & ANY_ELEMENT)) {
empty_xml:  ec_2.set_msg("password_list': ");
      password__list().XER_decode(Query_choice_password__list_xer_, p_reader, flavor_1, 0);
      if (!password__list().is_bound()) {
        TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "Failed to decode field.");
      }
    }
    else {
      ec_1.set_msg(" ");
      TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "'%s' does not match any alternative", elem_name);
      if (xml_depth >= 0) for (; rd_ok == 1 && p_reader.Depth() > xml_depth; rd_ok = p_reader.Read()) ;
    }
  }
  if ((e_xer || !is_record_of(p_flavor)) && own_tag)
  for (; rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_END_ELEMENT) {
      verify_end(p_reader, p_td, xml_depth, e_xer);
      rd_ok = p_reader.Read(); // one last time
      break;
    }
  }
  return 1;
}

int Query_choice::JSON_encode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok) const
{
  int enc_len = p_tok.put_next_token(JSON_TOKEN_OBJECT_START, NULL);

  switch(union_selection) {
  case ALT_password__list:
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "password_list");
    enc_len += field_password__list->JSON_encode(Query_choice_password__list_descr_, p_tok);
    break;
  case ALT_digest__list:
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "digest_list");
    enc_len += field_digest__list->JSON_encode(Query_choice_digest__list_descr_, p_tok);
    break;
  default:
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, 
      "Encoding an unbound value of type @jabber_iq_auth.Query.choice.");
    return -1;
  }

  enc_len += p_tok.put_next_token(JSON_TOKEN_OBJECT_END, NULL);
  return enc_len;
}

int Query_choice::JSON_decode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok, boolean p_silent)
{
  json_token_t j_token = JSON_TOKEN_NONE;
  int dec_len = p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_ERROR == j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }
  else if (JSON_TOKEN_OBJECT_START != j_token) {
    return JSON_ERROR_INVALID_TOKEN;
  }

  char* fld_name = 0;
  size_t name_len = 0;  dec_len += p_tok.get_next_token(&j_token, &fld_name, &name_len);
  if (JSON_TOKEN_NAME != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_NAME_TOKEN_ERROR);
    return JSON_ERROR_FATAL;
  } else {
    union_selection = UNBOUND_VALUE;
    if (0 == strncmp(fld_name, "password_list", name_len)) {
      int ret_val = password__list().JSON_decode(Query_choice_password__list_descr_, p_tok, p_silent);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "password_list");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += ret_val;
      }
    } else if (0 == strncmp(fld_name, "digest_list", name_len)) {
      int ret_val = digest__list().JSON_decode(Query_choice_digest__list_descr_, p_tok, p_silent);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "digest_list");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += ret_val;
      }
    } else {
      char* fld_name2 = mcopystrn(fld_name, name_len);
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_INVALID_NAME_ERROR, fld_name2);
      Free(fld_name2);
      return JSON_ERROR_FATAL;
    }
  }

  dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_OBJECT_END != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_STATIC_OBJECT_END_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }

  return dec_len;
}

void Query_choice_template::copy_value(const Query_choice& other_value)
{
single_value.union_selection = other_value.get_selection();
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
single_value.field_password__list = new Query_choice_password__list_template(other_value.password__list());
break;
case Query_choice::ALT_digest__list:
single_value.field_digest__list = new Query_choice_digest__list_template(other_value.digest__list());
break;
default:
TTCN_error("Initializing a template with an unbound value of type @jabber_iq_auth.Query.choice.");
}
set_selection(SPECIFIC_VALUE);
}

void Query_choice_template::copy_template(const Query_choice_template& other_value)
{
switch (other_value.template_selection) {
case SPECIFIC_VALUE:
single_value.union_selection = other_value.single_value.union_selection;
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
single_value.field_password__list = new Query_choice_password__list_template(*other_value.single_value.field_password__list);
break;
case Query_choice::ALT_digest__list:
single_value.field_digest__list = new Query_choice_digest__list_template(*other_value.single_value.field_digest__list);
break;
default:
TTCN_error("Internal error: Invalid union selector in a specific value when copying a template of type @jabber_iq_auth.Query.choice.");
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = other_value.value_list.n_values;
value_list.list_value = new Query_choice_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].copy_template(other_value.value_list.list_value[list_count]);
break;
default:
TTCN_error("Copying an uninitialized template of union type @jabber_iq_auth.Query.choice.");
}
set_selection(other_value);
}

Query_choice_template::Query_choice_template()
{
}

Query_choice_template::Query_choice_template(template_sel other_value)
 : Base_Template(other_value)
{
check_single_selection(other_value);
}

Query_choice_template::Query_choice_template(const Query_choice& other_value)
{
copy_value(other_value);
}

Query_choice_template::Query_choice_template(const OPTIONAL<Query_choice>& other_value)
{
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Query_choice&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Creating a template of union type @jabber_iq_auth.Query.choice from an unbound optional field.");
}
}

Query_choice_template::Query_choice_template(const Query_choice_template& other_value)
: Base_Template(){
copy_template(other_value);
}

Query_choice_template::~Query_choice_template()
{
clean_up();
}

void Query_choice_template::clean_up()
{
switch (template_selection) {
case SPECIFIC_VALUE:
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
delete single_value.field_password__list;
break;
case Query_choice::ALT_digest__list:
delete single_value.field_digest__list;
default:
break;
}
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
delete [] value_list.list_value;
default:
break;
}
template_selection = UNINITIALIZED_TEMPLATE;
}

Query_choice_template& Query_choice_template::operator=(template_sel other_value)
{
check_single_selection(other_value);
clean_up();
set_selection(other_value);
return *this;
}

Query_choice_template& Query_choice_template::operator=(const Query_choice& other_value)
{
clean_up();
copy_value(other_value);
return *this;
}

Query_choice_template& Query_choice_template::operator=(const OPTIONAL<Query_choice>& other_value)
{
clean_up();
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Query_choice&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Assignment of an unbound optional field to a template of union type @jabber_iq_auth.Query.choice.");
}
return *this;
}

Query_choice_template& Query_choice_template::operator=(const Query_choice_template& other_value)
{
if (&other_value != this) {
clean_up();
copy_template(other_value);
}
return *this;
}

boolean Query_choice_template::match(const Query_choice& other_value) const
{
if (!other_value.is_bound()) return FALSE;
switch (template_selection) {
case ANY_VALUE:
case ANY_OR_OMIT:
return TRUE;
case OMIT_VALUE:
return FALSE;
case SPECIFIC_VALUE:
{
Query_choice::union_selection_type value_selection = other_value.get_selection();
if (value_selection == Query_choice::UNBOUND_VALUE) return FALSE;
if (value_selection != single_value.union_selection) return FALSE;
switch (value_selection) {
case Query_choice::ALT_password__list:
return single_value.field_password__list->match(other_value.password__list());
case Query_choice::ALT_digest__list:
return single_value.field_digest__list->match(other_value.digest__list());
default:
TTCN_error("Internal error: Invalid selector in a specific value when matching a template of union type @jabber_iq_auth.Query.choice.");
}
}
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
if (value_list.list_value[list_count].match(other_value)) return template_selection == VALUE_LIST;
return template_selection == COMPLEMENTED_LIST;
default:
TTCN_error ("Matching an uninitialized template of union type @jabber_iq_auth.Query.choice.");
}
return FALSE;
}

boolean Query_choice_template::is_value() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent) return false;
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
return single_value.field_password__list->is_value();
case Query_choice::ALT_digest__list:
return single_value.field_digest__list->is_value();
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing is_value operation on a template of union type @jabber_iq_auth.Query.choice.");
}
}

Query_choice Query_choice_template::valueof() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent)
TTCN_error("Performing valueof or send operation on a non-specific template of union type @jabber_iq_auth.Query.choice.");
Query_choice ret_val;
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
ret_val.password__list() = single_value.field_password__list->valueof();
break;
case Query_choice::ALT_digest__list:
ret_val.digest__list() = single_value.field_digest__list->valueof();
break;
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing valueof operation on a template of union type @jabber_iq_auth.Query.choice.");
}
return ret_val;
}

Query_choice_template& Query_choice_template::list_item(unsigned int list_index) const
{
if (template_selection != VALUE_LIST && template_selection != COMPLEMENTED_LIST) TTCN_error("Internal error: Accessing a list element of a non-list template of union type @jabber_iq_auth.Query.choice.");
if (list_index >= value_list.n_values) TTCN_error("Internal error: Index overflow in a value list template of union type @jabber_iq_auth.Query.choice.");
return value_list.list_value[list_index];
}
void Query_choice_template::set_type(template_sel template_type, unsigned int list_length)
{
if (template_type != VALUE_LIST && template_type != COMPLEMENTED_LIST) TTCN_error ("Internal error: Setting an invalid list for a template of union type @jabber_iq_auth.Query.choice.");
clean_up();
set_selection(template_type);
value_list.n_values = list_length;
value_list.list_value = new Query_choice_template[list_length];
}

Query_choice_password__list_template& Query_choice_template::password__list()
{
if (template_selection != SPECIFIC_VALUE || single_value.union_selection != Query_choice::ALT_password__list) {
template_sel old_selection = template_selection;
clean_up();
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) single_value.field_password__list = new Query_choice_password__list_template(ANY_VALUE);
else single_value.field_password__list = new Query_choice_password__list_template;
single_value.union_selection = Query_choice::ALT_password__list;
set_selection(SPECIFIC_VALUE);
}
return *single_value.field_password__list;
}

const Query_choice_password__list_template& Query_choice_template::password__list() const
{
if (template_selection != SPECIFIC_VALUE) TTCN_error("Accessing field password_list in a non-specific template of union type @jabber_iq_auth.Query.choice.");
if (single_value.union_selection != Query_choice::ALT_password__list) TTCN_error("Accessing non-selected field password_list in a template of union type @jabber_iq_auth.Query.choice.");
return *single_value.field_password__list;
}

Query_choice_digest__list_template& Query_choice_template::digest__list()
{
if (template_selection != SPECIFIC_VALUE || single_value.union_selection != Query_choice::ALT_digest__list) {
template_sel old_selection = template_selection;
clean_up();
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) single_value.field_digest__list = new Query_choice_digest__list_template(ANY_VALUE);
else single_value.field_digest__list = new Query_choice_digest__list_template;
single_value.union_selection = Query_choice::ALT_digest__list;
set_selection(SPECIFIC_VALUE);
}
return *single_value.field_digest__list;
}

const Query_choice_digest__list_template& Query_choice_template::digest__list() const
{
if (template_selection != SPECIFIC_VALUE) TTCN_error("Accessing field digest_list in a non-specific template of union type @jabber_iq_auth.Query.choice.");
if (single_value.union_selection != Query_choice::ALT_digest__list) TTCN_error("Accessing non-selected field digest_list in a template of union type @jabber_iq_auth.Query.choice.");
return *single_value.field_digest__list;
}

boolean Query_choice_template::ischosen(Query_choice::union_selection_type checked_selection) const
{
if (checked_selection == Query_choice::UNBOUND_VALUE) TTCN_error("Internal error: Performing ischosen() operation on an invalid field of union type @jabber_iq_auth.Query.choice.");
switch (template_selection) {
case SPECIFIC_VALUE:
if (single_value.union_selection == Query_choice::UNBOUND_VALUE) TTCN_error("Internal error: Invalid selector in a specific value when performing ischosen() operation on a template of union type @jabber_iq_auth.Query.choice.");
return single_value.union_selection == checked_selection;
case VALUE_LIST:
{
if (value_list.n_values < 1)
TTCN_error("Internal error: Performing ischosen() operation on a template of union type @jabber_iq_auth.Query.choice containing an empty list.");
boolean ret_val = value_list.list_value[0].ischosen(checked_selection);
boolean all_same = TRUE;
for (unsigned int list_count = 1; list_count < value_list.n_values; list_count++) {
if (value_list.list_value[list_count].ischosen(checked_selection) != ret_val) {
all_same = FALSE;
break;
}
}
if (all_same) return ret_val;
}
case ANY_VALUE:
case ANY_OR_OMIT:
case OMIT_VALUE:
case COMPLEMENTED_LIST:
TTCN_error("Performing ischosen() operation on a template of union type @jabber_iq_auth.Query.choice, which does not determine unambiguously the chosen field of the matching values.");
default:
TTCN_error("Performing ischosen() operation on an uninitialized template of union type @jabber_iq_auth.Query.choice");
}
return FALSE;
}

void Query_choice_template::log() const
{
switch (template_selection) {
case SPECIFIC_VALUE:
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
TTCN_Logger::log_event_str("{ password_list := ");
single_value.field_password__list->log();
TTCN_Logger::log_event_str(" }");
break;
case Query_choice::ALT_digest__list:
TTCN_Logger::log_event_str("{ digest_list := ");
single_value.field_digest__list->log();
TTCN_Logger::log_event_str(" }");
break;
default:
TTCN_Logger::log_event_str("<invalid selector>");
}
break;
case COMPLEMENTED_LIST:
TTCN_Logger::log_event_str("complement ");
case VALUE_LIST:
TTCN_Logger::log_char('(');
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++) {
if (list_count > 0) TTCN_Logger::log_event_str(", ");
value_list.list_value[list_count].log();
}
TTCN_Logger::log_char(')');
break;
default:
log_generic();
}
log_ifpresent();
}

void Query_choice_template::log_match(const Query_choice& match_value) const
{
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity() && match(match_value)){
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str(" matched");
return;
}
if (template_selection == SPECIFIC_VALUE && single_value.union_selection == match_value.get_selection()) {
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
TTCN_Logger::log_logmatch_info(".password_list");
single_value.field_password__list->log_match(match_value.password__list());
} else {
TTCN_Logger::log_event_str("{ password_list := ");
single_value.field_password__list->log_match(match_value.password__list());
TTCN_Logger::log_event_str(" }");
}
break;
case Query_choice::ALT_digest__list:
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
TTCN_Logger::log_logmatch_info(".digest_list");
single_value.field_digest__list->log_match(match_value.digest__list());
} else {
TTCN_Logger::log_event_str("{ digest_list := ");
single_value.field_digest__list->log_match(match_value.digest__list());
TTCN_Logger::log_event_str(" }");
}
break;
default:
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str("<invalid selector>");
}
} else {
TTCN_Logger::print_logmatch_buffer();
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
if (match(match_value)) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
}

void Query_choice_template::encode_text(Text_Buf& text_buf) const
{
encode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
text_buf.push_int(single_value.union_selection);
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
single_value.field_password__list->encode_text(text_buf);
break;
case Query_choice::ALT_digest__list:
single_value.field_digest__list->encode_text(text_buf);
break;
default:
TTCN_error("Internal error: Invalid selector in a specific value when encoding a template of union type @jabber_iq_auth.Query.choice.");
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
text_buf.push_int(value_list.n_values);
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an uninitialized template of type @jabber_iq_auth.Query.choice.");
}
}

void Query_choice_template::decode_text(Text_Buf& text_buf)
{
clean_up();
decode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
{
single_value.union_selection = Query_choice::UNBOUND_VALUE;
Query_choice::union_selection_type new_selection = (Query_choice::union_selection_type)text_buf.pull_int().get_val();
switch (new_selection) {
case Query_choice::ALT_password__list:
single_value.field_password__list = new Query_choice_password__list_template;
single_value.field_password__list->decode_text(text_buf);
break;
case Query_choice::ALT_digest__list:
single_value.field_digest__list = new Query_choice_digest__list_template;
single_value.field_digest__list->decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized union selector was received for a template of type @jabber_iq_auth.Query.choice.");
}
single_value.union_selection = new_selection;
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = text_buf.pull_int().get_val();
value_list.list_value = new Query_choice_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized selector was received in a template of type @jabber_iq_auth.Query.choice.");
}
}

boolean Query_choice_template::is_present() const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return FALSE;
return !match_omit();
}

boolean Query_choice_template::match_omit() const
{
if (is_ifpresent) return TRUE;
switch (template_selection) {
case OMIT_VALUE:
case ANY_OR_OMIT:
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int v_idx=0; v_idx<value_list.n_values; v_idx++)
if (value_list.list_value[v_idx].match_omit())
return template_selection==VALUE_LIST;
return template_selection==COMPLEMENTED_LIST;
default:
return FALSE;
}
return FALSE;
}

void Query_choice_template::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for union template type `@jabber_iq_auth.Query.choice'");
    }
    if (strcmp("password_list", param_field) == 0) {
      password__list().set_param(param);
      return;
    } else if (strcmp("digest_list", param_field) == 0) {
      digest__list().set_param(param);
      return;
    } else param.error("Field `%s' not found in union template type `@jabber_iq_auth.Query.choice'", param_field);
  }
  param.basic_check(Module_Param::BC_TEMPLATE, "union template");
  switch (param.get_type()) {
  case Module_Param::MP_Omit:
    *this = OMIT_VALUE;
    break;
  case Module_Param::MP_Any:
    *this = ANY_VALUE;
    break;
  case Module_Param::MP_AnyOrNone:
    *this = ANY_OR_OMIT;
    break;
  case Module_Param::MP_List_Template:
  case Module_Param::MP_ComplementList_Template:
    set_type(param.get_type()==Module_Param::MP_List_Template ? VALUE_LIST : COMPLEMENTED_LIST, param.get_size());
    for (size_t p_i=0; p_i<param.get_size(); p_i++) {
      list_item(p_i).set_param(*param.get_elem(p_i));
    }
    break;
  case Module_Param::MP_Value_List:
    if (param.get_size()==0) break;
    param.type_error("union template", "@jabber_iq_auth.Query.choice");
    break;
  case Module_Param::MP_Assignment_List: {
    Module_Param* mp_last = param.get_elem(param.get_size()-1);
    if (!strcmp(mp_last->get_id()->get_name(), "password_list")) {
      password__list().set_param(*mp_last);
      break;
    }
    if (!strcmp(mp_last->get_id()->get_name(), "digest_list")) {
      digest__list().set_param(*mp_last);
      break;
    }
    mp_last->error("Field %s does not exist in type @jabber_iq_auth.Query.choice.", mp_last->get_id()->get_name());
  } break;
  default:
    param.type_error("union template", "@jabber_iq_auth.Query.choice");
  }
  is_ifpresent = param.get_ifpresent();
}

void Query_choice_template::check_restriction(template_res t_res, const char* t_name) const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return;
switch ((t_name&&(t_res==TR_VALUE))?TR_OMIT:t_res) {
case TR_OMIT:
if (template_selection==OMIT_VALUE) return;
case TR_VALUE:
if (template_selection!=SPECIFIC_VALUE || is_ifpresent) break;
switch (single_value.union_selection) {
case Query_choice::ALT_password__list:
single_value.field_password__list->check_restriction(t_res, t_name ? t_name : "@jabber_iq_auth.Query.choice");
return;
case Query_choice::ALT_digest__list:
single_value.field_digest__list->check_restriction(t_res, t_name ? t_name : "@jabber_iq_auth.Query.choice");
return;
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing check_restriction operation on a template of union type @jabber_iq_auth.Query.choice.");
}
case TR_PRESENT:
if (!match_omit()) return;
break;
default:
return;
}
TTCN_error("Restriction `%s' on template of type %s violated.", get_res_name(t_res), t_name ? t_name : "@jabber_iq_auth.Query.choice");
}

Query::Query()
{
  bound_flag = FALSE;
}

Query::Query(const OPTIONAL<UNIVERSAL_CHARSTRING>& par_username,
    const Query_choice& par_choice,
    const OPTIONAL<UNIVERSAL_CHARSTRING>& par_resource)
  :   field_username(par_username),
  field_choice(par_choice),
  field_resource(par_resource)
{
  bound_flag = TRUE;
}

Query::Query(const Query& other_value)
{
if(!other_value.is_bound()) TTCN_error("Copying an unbound value of type @jabber_iq_auth.Query.");
bound_flag = TRUE;
if (other_value.username().is_bound()) field_username = other_value.username();
else field_username.clean_up();
if (other_value.choice().is_bound()) field_choice = other_value.choice();
else field_choice.clean_up();
if (other_value.resource().is_bound()) field_resource = other_value.resource();
else field_resource.clean_up();
}

void Query::clean_up()
{
field_username.clean_up();
field_choice.clean_up();
field_resource.clean_up();
bound_flag = FALSE;
}

Query& Query::operator=(const Query& other_value)
{
if (this != &other_value) {
  if(!other_value.is_bound()) TTCN_error("Assignment of an unbound value of type @jabber_iq_auth.Query.");
  bound_flag = TRUE;
  if (other_value.username().is_bound()) field_username = other_value.username();
  else field_username.clean_up();
  if (other_value.choice().is_bound()) field_choice = other_value.choice();
  else field_choice.clean_up();
  if (other_value.resource().is_bound()) field_resource = other_value.resource();
  else field_resource.clean_up();
}
return *this;
}

boolean Query::operator==(const Query& other_value) const
{
if (!is_bound() && !other_value.is_bound()) return TRUE;
return field_username==other_value.field_username
  && field_choice==other_value.field_choice
  && field_resource==other_value.field_resource;
}

boolean Query::is_bound() const
{
if (bound_flag) return TRUE;
if(OPTIONAL_OMIT == field_username.get_selection() || field_username.is_bound()) return TRUE;
if(field_choice.is_bound()) return TRUE;
if(OPTIONAL_OMIT == field_resource.get_selection() || field_resource.is_bound()) return TRUE;
return FALSE;
}
boolean Query::is_value() const
{
if (!is_bound()) return FALSE;
if(OPTIONAL_OMIT != field_username.get_selection() && !field_username.is_value()) return FALSE;
if(!field_choice.is_value()) return FALSE;
if(OPTIONAL_OMIT != field_resource.get_selection() && !field_resource.is_value()) return FALSE;
return TRUE;
}
int Query::size_of() const
{
  if (!is_bound()) TTCN_error("Calculating the size of an unbound record/set value of type @jabber_iq_auth.Query");
  int ret_val = 1;
  if (field_username.ispresent()) ret_val++;
  if (field_resource.ispresent()) ret_val++;
  return ret_val;
}

void Query::log() const
{
if (!is_bound()) {
TTCN_Logger::log_event_unbound();
return;
}
TTCN_Logger::log_event_str("{ username := ");
field_username.log();
TTCN_Logger::log_event_str(", choice := ");
field_choice.log();
TTCN_Logger::log_event_str(", resource := ");
field_resource.log();
TTCN_Logger::log_event_str(" }");
}

void Query::set_param(Module_Param& param)
{
  bound_flag = TRUE;
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for record type `@jabber_iq_auth.Query'");
    }
    if (strcmp("username", param_field) == 0) {
      username().set_param(param);
      return;
    } else if (strcmp("choice", param_field) == 0) {
      choice().set_param(param);
      return;
    } else if (strcmp("resource", param_field) == 0) {
      resource().set_param(param);
      return;
    } else param.error("Field `%s' not found in record type `@jabber_iq_auth.Query'", param_field);
  }
  param.basic_check(Module_Param::BC_VALUE, "record value");
  switch (param.get_type()) {
  case Module_Param::MP_Value_List:
    if (3<param.get_size()) {
      param.error("record value of type @jabber_iq_auth.Query has 3 fields but list value has %d fields", (int)param.get_size());
    }
    if (param.get_size()>0 && param.get_elem(0)->get_type()!=Module_Param::MP_NotUsed) username().set_param(*param.get_elem(0));
    if (param.get_size()>1 && param.get_elem(1)->get_type()!=Module_Param::MP_NotUsed) choice().set_param(*param.get_elem(1));
    if (param.get_size()>2 && param.get_elem(2)->get_type()!=Module_Param::MP_NotUsed) resource().set_param(*param.get_elem(2));
    break;
  case Module_Param::MP_Assignment_List: {
    Vector<bool> value_used(param.get_size());
    value_used.resize(param.get_size(), false);
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "username")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          username().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "choice")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          choice().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "resource")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          resource().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) if (!value_used[val_idx]) {
      param.get_elem(val_idx)->error("Non existent field name in type @jabber_iq_auth.Query: %s", param.get_elem(val_idx)->get_id()->get_name());
      break;
    }
  } break;
  default:
    param.type_error("record value", "@jabber_iq_auth.Query");
  }
}

void Query::set_implicit_omit()
{
if (!username().is_bound()) username() = OMIT_VALUE;
else username().set_implicit_omit();
if (choice().is_bound()) choice().set_implicit_omit();
if (!resource().is_bound()) resource() = OMIT_VALUE;
else resource().set_implicit_omit();
}

void Query::encode_text(Text_Buf& text_buf) const
{
if (!is_bound()) TTCN_error("Text encoder: Encoding an unbound record/set value of type @jabber_iq_auth.Query.");
field_username.encode_text(text_buf);
field_choice.encode_text(text_buf);
field_resource.encode_text(text_buf);
}

void Query::decode_text(Text_Buf& text_buf)
{
bound_flag = TRUE;
field_username.decode_text(text_buf);
field_choice.decode_text(text_buf);
field_resource.decode_text(text_buf);
}

void Query::encode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...) const
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-encoding type '%s': ", p_td.name);
    unsigned BER_coding=va_arg(pvar, unsigned);
    BER_encode_chk_coding(BER_coding);
    ASN_BER_TLV_t *tlv=BER_encode_TLV(p_td, BER_coding);
    tlv->put_in_buffer(p_buf);
    ASN_BER_TLV_t::destruct(tlv);
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-encoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    RAW_enc_tr_pos rp;
    rp.level=0;
    rp.pos=NULL;
    RAW_enc_tree root(FALSE, NULL, &rp, 1, p_td.raw);
    RAW_encode(p_td, root);
    root.put_to_buf(p_buf);
    break;}
  case TTCN_EncDec::CT_TEXT: {
    TTCN_EncDec_ErrorContext ec("While TEXT-encoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
      ("No TEXT descriptor available for type '%s'.", p_td.name);
    TEXT_encode(p_td,p_buf);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-encoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XER_encode(*(p_td.xer),p_buf, XER_coding, 0, 0);
    p_buf.put_c('\n');
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-encoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok(va_arg(pvar, int) != 0);
    JSON_encode(p_td, tok);
    p_buf.put_s(tok.get_buffer_length(), (const unsigned char*)tok.get_buffer());
    break;}
  default:
    TTCN_error("Unknown coding method requested to encode type '%s'", p_td.name);
  }
  va_end(pvar);
}

void Query::decode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...)
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-decoding type '%s': ", p_td.name);
    unsigned L_form=va_arg(pvar, unsigned);
    ASN_BER_TLV_t tlv;
    BER_decode_str2TLV(p_buf, tlv, L_form);
    BER_decode_TLV(p_td, tlv, L_form);
    if(tlv.isComplete) p_buf.increase_pos(tlv.get_len());
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-decoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    raw_order_t r_order;
    switch(p_td.raw->top_bit_order) {
    case TOP_BIT_LEFT:
      r_order=ORDER_LSB;
      break;
    case TOP_BIT_RIGHT:
    default:
      r_order=ORDER_MSB;
    }
    int rawr = RAW_decode(p_td, p_buf, p_buf.get_len()*8, r_order);
    if(rawr<0) switch (-rawr) {
    case TTCN_EncDec::ET_INCOMPL_MSG:
    case TTCN_EncDec::ET_LEN_ERR:
      ec.error((TTCN_EncDec::error_type_t)-rawr, "Can not decode type '%s', because incomplete message was received", p_td.name);
      break;
    case 1:
    default:
      ec.error(TTCN_EncDec::ET_INVAL_MSG, "Can not decode type '%s', because invalid message was received", p_td.name);
      break;
    }
    break;}
  case TTCN_EncDec::CT_TEXT: {
    Limit_Token_List limit;
    TTCN_EncDec_ErrorContext ec("While TEXT-decoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
        ("No TEXT descriptor available for type '%s'.", p_td.name);
    const unsigned char *b_data=p_buf.get_data();
    if(b_data[p_buf.get_len()-1]!='\0'){
      p_buf.set_pos(p_buf.get_len());
      p_buf.put_zero(8,ORDER_LSB);
      p_buf.rewind();
    }
    if(TEXT_decode(p_td,p_buf,limit)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-decoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XmlReaderWrap reader(p_buf);
    for (int rd_ok=reader.Read(); rd_ok==1; rd_ok=reader.Read()) {
      if (reader.NodeType() == XML_READER_TYPE_ELEMENT) break;
    }
    XER_decode(*(p_td.xer), reader, XER_coding | XER_TOPLEVEL, 0);
    size_t bytes = reader.ByteConsumed();
    p_buf.set_pos(bytes);
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-decoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok((const char*)p_buf.get_data(), p_buf.get_len());
    if(JSON_decode(p_td, tok, false)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    p_buf.set_pos(tok.get_buf_pos());
    break;}
  default:
    TTCN_error("Unknown coding method requested to decode type '%s'", p_td.name);
  }
  va_end(pvar);
}

char ** Query::collect_ns(const XERdescriptor_t& p_td, size_t& num_ns, bool& def_ns) const {
  size_t num_collected;
  char **collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
  try {
  char **new_ns;
  size_t num_new;
  bool def_ns_1 = false;
  new_ns = field_username.collect_ns(Query_username_xer_, num_new, def_ns);
  merge_ns(collected_ns, num_collected, new_ns, num_new);
  def_ns = def_ns || def_ns_1;
  new_ns = field_choice.collect_ns(Query_choice_xer_, num_new, def_ns);
  merge_ns(collected_ns, num_collected, new_ns, num_new);
  def_ns = def_ns || def_ns_1;
  new_ns = field_resource.collect_ns(Query_resource_xer_, num_new, def_ns);
  merge_ns(collected_ns, num_collected, new_ns, num_new);
  def_ns = def_ns || def_ns_1;
  }
  catch (...) {
    while (num_collected > 0) Free(collected_ns[--num_collected]);
    Free(collected_ns);
    throw;
  }
  num_ns = num_collected;
  return collected_ns;
}

boolean Query::can_start(const char *name, const char *uri, const XERdescriptor_t& xd, unsigned int flavor) {
  boolean e_xer = is_exer(flavor &= ~XER_RECOF);
  if (!e_xer || !((xd.xer_bits & UNTAGGED) || (flavor & (USE_NIL|XER_RECOF)))) return check_name(name, xd, e_xer) && (!e_xer || check_namespace(uri, xd));
  else if (UNIVERSAL_CHARSTRING::can_start(name, uri, Query_username_xer_, flavor)) return true;
  else if (Query_choice::can_start(name, uri, Query_choice_xer_, flavor)) return true;
  return false;
}

int Query::XER_encode(const XERdescriptor_t& p_td, TTCN_Buffer& p_buf, unsigned int p_flavor, int p_indent, embed_values_enc_struct_t*) const
{
  if (!is_bound()) TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, "Encoding an unbound value.");
  TTCN_EncDec_ErrorContext ec_0("Component '");
  TTCN_EncDec_ErrorContext ec_1;
  int encoded_length=(int)p_buf.get_len();
  int e_xer = is_exer(p_flavor);
  const boolean omit_tag = e_xer && p_indent && ((p_td.xer_bits & (UNTAGGED|XER_ATTRIBUTE)) || (p_flavor & (USE_NIL|USE_TYPE_ATTR)));
  if (e_xer && (p_td.xer_bits & EMBED_VALUES)) p_flavor |= XER_CANONICAL;
  int is_indented = !is_canonical(p_flavor);
  const boolean need_control_ns = (p_td.xer_bits & (USE_NIL));
  size_t num_collected = 0;
  char **collected_ns = NULL;
  bool def_ns = false;
  if (e_xer) {
    if (p_indent == 0) {
      collected_ns = collect_ns(p_td, num_collected, def_ns);
    }
    else if ((p_flavor & DEF_NS_SQUASHED) && p_td.my_module && p_td.ns_index != -1){
      const namespace_t * ns = p_td.my_module->get_ns(p_td.ns_index);
      if (*ns->px == '\0') {
        collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
      }
    }
  }
  const boolean empty_ns_hack = e_xer && !omit_tag && (p_indent > 0)
    && (p_td.xer_bits & FORM_UNQUALIFIED)
    && p_td.my_module && p_td.ns_index != -1
    && *p_td.my_module->get_ns(p_td.ns_index)->px == '\0';
  const boolean delay_close = e_xer && (need_control_ns || num_collected || empty_ns_hack);
  size_t chopped_chars = 0;
  if (!omit_tag) {
    if (is_indented) do_indent(p_buf, p_indent);
    p_buf.put_c('<');
    if (e_xer) write_ns_prefix(p_td, p_buf);
    p_buf.put_s((size_t)p_td.namelens[e_xer]-(delay_close || (e_xer && (p_td.xer_bits & HAS_1UNTAGGED)))-(!is_indented || delay_close), (cbyte*)p_td.names[e_xer]);
  }
  else if (p_flavor & USE_TYPE_ATTR) {
    size_t buf_len = p_buf.get_len();
    const unsigned char * const buf_data = p_buf.get_data();
    if (buf_data[buf_len-1-chopped_chars] == '\n') ++chopped_chars;
    if (buf_data[buf_len-1-chopped_chars] == '>' ) ++chopped_chars;
    if (chopped_chars) {
      p_buf.increase_length(-chopped_chars);
    }
  }
  int sub_len=0;
  p_flavor &= XER_MASK;
  { // !QN
  if (e_xer && num_collected) {
    size_t num_ns;
    for (num_ns = 0; num_ns < num_collected; ++num_ns) {
      p_buf.put_s(strlen(collected_ns[num_ns]), (cbyte*)collected_ns[num_ns]);
      Free(collected_ns[num_ns]);
    }
    Free(collected_ns);
  }

  if (def_ns) {
    p_flavor &= ~DEF_NS_SQUASHED;
    p_flavor |=  DEF_NS_PRESENT;
  }
  else if (empty_ns_hack) {
    p_buf.put_s(9, (cbyte*)" xmlns=''");
    p_flavor &= ~DEF_NS_PRESENT;
    p_flavor |=  DEF_NS_SQUASHED;
  }
  if (delay_close && (!omit_tag || chopped_chars)) p_buf.put_s(1+is_indented, (cbyte*)">\n");
  ec_1.set_msg("username': ");
  sub_len += field_username.XER_encode(Query_username_xer_, p_buf, p_flavor, p_indent+!omit_tag, 0);
  ec_1.set_msg("choice': ");
  sub_len += field_choice.XER_encode(Query_choice_xer_, p_buf, p_flavor, p_indent+!omit_tag, 0);
  ec_1.set_msg("resource': ");
  sub_len += field_resource.XER_encode(Query_resource_xer_, p_buf, p_flavor, p_indent+!omit_tag, 0);
  } // QN?
  if (!omit_tag) {
  if (sub_len) {
    if (is_indented && !(e_xer && (p_td.xer_bits & (HAS_1UNTAGGED | USE_QNAME)))) {
      switch ((int)(e_xer && (p_td.xer_bits & USE_NIL))) {
      case 1: {
        const unsigned char *buf_end = p_buf.get_data() + (p_buf.get_len()-1);
        if (buf_end[-1] != '>' || *buf_end != '\n') break;
      }
      case 0:
        do_indent(p_buf, p_indent);
        break;
      }
    }
    p_buf.put_c('<');
    p_buf.put_c('/');
    if (e_xer) write_ns_prefix(p_td, p_buf);
    p_buf.put_s((size_t)p_td.namelens[e_xer]-!is_indented, (cbyte*)p_td.names[e_xer]);
  } else {
    p_buf.increase_length(-is_indented-1);
    p_buf.put_s((size_t)2+is_indented, (cbyte*)"/>\n");
  }}
  return (int)p_buf.get_len() - encoded_length;
}

int Query::XER_decode(const XERdescriptor_t& p_td, XmlReaderWrap& p_reader, unsigned int p_flavor, embed_values_dec_struct_t*)
{
  bound_flag = TRUE;
  int e_xer = is_exer(p_flavor);
  int xerbits = p_td.xer_bits;
  if (p_flavor & XER_TOPLEVEL) xerbits &= ~UNTAGGED;
  const boolean omit_tag = e_xer && ((xerbits & (UNTAGGED|XER_ATTRIBUTE)) || (p_flavor & (USE_NIL|USE_TYPE_ATTR)));
  boolean tag_closed = (p_flavor & PARENT_CLOSED) != 0;
  const boolean parent_tag = e_xer && (p_flavor & (USE_TYPE_ATTR));
  (void)parent_tag;
  p_flavor &= XER_MASK;
  int rd_ok, xml_depth=-1, type;
  {
  TTCN_EncDec_ErrorContext ec_0("Component '");
  TTCN_EncDec_ErrorContext ec_1;
  if (!omit_tag) for (rd_ok=p_reader.Ok(); rd_ok==1; rd_ok=p_reader.Read()) {
    type = p_reader.NodeType();
    if (type==XML_READER_TYPE_ELEMENT) {
      verify_name(p_reader, p_td, e_xer);
      xml_depth = p_reader.Depth();
      tag_closed = p_reader.IsEmptyElement();
      break;
    }
  }
  if ((!omit_tag || parent_tag) && !p_reader.IsEmptyElement()) rd_ok = p_reader.Read();
  {
    ec_1.set_msg("username': ");
    field_username.XER_decode(Query_username_xer_, p_reader, p_flavor | (p_td.xer_bits & USE_NIL)| (tag_closed ? PARENT_CLOSED : 0), 0);
  }
  {
    ec_1.set_msg("choice': ");
    field_choice.XER_decode(Query_choice_xer_, p_reader, p_flavor | (p_td.xer_bits & USE_NIL)| (tag_closed ? PARENT_CLOSED : 0), 0);
  }
  if (e_xer && p_td.dfeValue && p_reader.IsEmptyElement()) {
    field_resource = *static_cast<const UNIVERSAL_CHARSTRING*>(p_td.dfeValue);
  }
  else  {
    ec_1.set_msg("resource': ");
    field_resource.XER_decode(Query_resource_xer_, p_reader, p_flavor | (p_td.xer_bits & USE_NIL)| (tag_closed ? PARENT_CLOSED : 0), 0);
  }
  } // errorcontext
  if (!omit_tag) {
    int current_depth;
    for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
      type = p_reader.NodeType();
      if ((current_depth = p_reader.Depth()) > xml_depth) {
        if (XML_READER_TYPE_ELEMENT == type) {
          TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_TAG,
              "Unprocessed XML tag `%s'", (const char *)p_reader.Name());
        }
        continue;
      }
      else if (current_depth == xml_depth) {
        if (XML_READER_TYPE_ELEMENT == type) {
          verify_name(p_reader, p_td, e_xer);
          if (p_reader.IsEmptyElement()) {
            p_reader.Read();
            break;
          }
        }
        else if (XML_READER_TYPE_END_ELEMENT == type) {
          verify_end(p_reader, p_td, xml_depth, e_xer);
          rd_ok = p_reader.Read();
          break;
        }
      }
      else break;    }
  }
  return 1;
}

int Query::JSON_encode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok) const
{
  if (!is_bound()) {
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND,
      "Encoding an unbound value of type @jabber_iq_auth.Query.");
    return -1;
  }

  int enc_len = p_tok.put_next_token(JSON_TOKEN_OBJECT_START, NULL);

  if (field_username.is_present())
  {
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "username");
    enc_len += field_username.JSON_encode(Query_username_descr_, p_tok);
  }

  {
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "choice");
    enc_len += field_choice.JSON_encode(Query_choice_descr_, p_tok);
  }

  if (field_resource.is_present())
  {
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "resource");
    enc_len += field_resource.JSON_encode(Query_resource_descr_, p_tok);
  }

  enc_len += p_tok.put_next_token(JSON_TOKEN_OBJECT_END, NULL);
  return enc_len;
}

int Query::JSON_decode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok, boolean p_silent)
{
  json_token_t j_token = JSON_TOKEN_NONE;
  int dec_len = p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_ERROR == j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }
  else if (JSON_TOKEN_OBJECT_START != j_token) {
    return JSON_ERROR_INVALID_TOKEN;
  }
  bound_flag = TRUE;

  while (true) {
    char* fld_name = 0;
    size_t name_len = 0;
    size_t buf_pos = p_tok.get_buf_pos();
    dec_len += p_tok.get_next_token(&j_token, &fld_name, &name_len);
    if (JSON_TOKEN_ERROR == j_token) {
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_NAME_TOKEN_ERROR);
      return JSON_ERROR_FATAL;
    }
    else if (JSON_TOKEN_NAME != j_token) {
      p_tok.set_buf_pos(buf_pos);
      break;
    }
    else {
      if (8 == name_len && 0 == strncmp(fld_name, "username", name_len)) {
        int ret_val = field_username.JSON_decode(Query_username_descr_, p_tok, p_silent);
        if (0 > ret_val) {
          if (JSON_ERROR_INVALID_TOKEN) {
            JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "username");
          }
          return JSON_ERROR_FATAL;
        }
        dec_len += ret_val;
      } else if (6 == name_len && 0 == strncmp(fld_name, "choice", name_len)) {
        int ret_val = field_choice.JSON_decode(Query_choice_descr_, p_tok, p_silent);
        if (0 > ret_val) {
          if (JSON_ERROR_INVALID_TOKEN) {
            JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "choice");
          }
          return JSON_ERROR_FATAL;
        }
        dec_len += ret_val;
      } else if (8 == name_len && 0 == strncmp(fld_name, "resource", name_len)) {
        int ret_val = field_resource.JSON_decode(Query_resource_descr_, p_tok, p_silent);
        if (0 > ret_val) {
          if (JSON_ERROR_INVALID_TOKEN) {
            JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "resource");
          }
          return JSON_ERROR_FATAL;
        }
        dec_len += ret_val;
      } else {
        char* fld_name2 = mcopystrn(fld_name, name_len);
        JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_INVALID_NAME_ERROR, fld_name2);
        dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
        if (JSON_TOKEN_NUMBER != j_token && JSON_TOKEN_STRING != j_token &&
            JSON_TOKEN_LITERAL_TRUE != j_token && JSON_TOKEN_LITERAL_FALSE != j_token &&
            JSON_TOKEN_LITERAL_NULL != j_token) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, fld_name2);
          Free(fld_name2);
          return JSON_ERROR_FATAL;
        }
        Free(fld_name2);
      }
    }
  }

  dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_OBJECT_END != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_OBJECT_END_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }

  if (!field_username.is_bound()) {
    field_username = OMIT_VALUE;
  }
  if (!field_choice.is_bound()) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_MISSING_FIELD_ERROR, "choice");
    return JSON_ERROR_FATAL;
  }
  if (!field_resource.is_bound()) {
    field_resource = OMIT_VALUE;
  }

  return dec_len;
}

struct Query_template::single_value_struct {
UNIVERSAL_CHARSTRING_template field_username;
Query_choice_template field_choice;
UNIVERSAL_CHARSTRING_template field_resource;
};

void Query_template::set_specific()
{
if (template_selection != SPECIFIC_VALUE) {
template_sel old_selection = template_selection;
clean_up();
single_value = new single_value_struct;
set_selection(SPECIFIC_VALUE);
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) {
single_value->field_username = ANY_OR_OMIT;
single_value->field_choice = ANY_VALUE;
single_value->field_resource = ANY_OR_OMIT;
}
}
}

void Query_template::copy_value(const Query& other_value)
{
single_value = new single_value_struct;
if (other_value.username().is_bound()) {
  if (other_value.username().ispresent()) single_value->field_username = other_value.username()();
  else single_value->field_username = OMIT_VALUE;
} else {
  single_value->field_username.clean_up();
}
if (other_value.choice().is_bound()) {
  single_value->field_choice = other_value.choice();
} else {
  single_value->field_choice.clean_up();
}
if (other_value.resource().is_bound()) {
  if (other_value.resource().ispresent()) single_value->field_resource = other_value.resource()();
  else single_value->field_resource = OMIT_VALUE;
} else {
  single_value->field_resource.clean_up();
}
set_selection(SPECIFIC_VALUE);
}

void Query_template::copy_template(const Query_template& other_value)
{
switch (other_value.template_selection) {
case SPECIFIC_VALUE:
single_value = new single_value_struct;
if (UNINITIALIZED_TEMPLATE != other_value.username().get_selection()) {
single_value->field_username = other_value.username();
} else {
single_value->field_username.clean_up();
}
if (UNINITIALIZED_TEMPLATE != other_value.choice().get_selection()) {
single_value->field_choice = other_value.choice();
} else {
single_value->field_choice.clean_up();
}
if (UNINITIALIZED_TEMPLATE != other_value.resource().get_selection()) {
single_value->field_resource = other_value.resource();
} else {
single_value->field_resource.clean_up();
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = other_value.value_list.n_values;
value_list.list_value = new Query_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].copy_template(other_value.value_list.list_value[list_count]);
break;
default:
TTCN_error("Copying an uninitialized/unsupported template of type @jabber_iq_auth.Query.");
break;
}
set_selection(other_value);
}

Query_template::Query_template()
{
}

Query_template::Query_template(template_sel other_value)
 : Base_Template(other_value)
{
check_single_selection(other_value);
}

Query_template::Query_template(const Query& other_value)
{
copy_value(other_value);
}

Query_template::Query_template(const OPTIONAL<Query>& other_value)
{
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Query&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Creating a template of type @jabber_iq_auth.Query from an unbound optional field.");
}
}

Query_template::Query_template(const Query_template& other_value)
: Base_Template()
{
copy_template(other_value);
}

Query_template::~Query_template()
{
clean_up();
}

Query_template& Query_template::operator=(template_sel other_value)
{
check_single_selection(other_value);
clean_up();
set_selection(other_value);
return *this;
}

Query_template& Query_template::operator=(const Query& other_value)
{
clean_up();
copy_value(other_value);
return *this;
}

Query_template& Query_template::operator=(const OPTIONAL<Query>& other_value)
{
clean_up();
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Query&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Assignment of an unbound optional field to a template of type @jabber_iq_auth.Query.");
}
return *this;
}

Query_template& Query_template::operator=(const Query_template& other_value)
{
if (&other_value != this) {
clean_up();
copy_template(other_value);
}
return *this;
}

boolean Query_template::match(const Query& other_value) const
{
if (!other_value.is_bound()) return FALSE;
switch (template_selection) {
case ANY_VALUE:
case ANY_OR_OMIT:
return TRUE;
case OMIT_VALUE:
return FALSE;
case SPECIFIC_VALUE:
if(!other_value.username().is_bound()) return FALSE;
if((other_value.username().ispresent() ? !single_value->field_username.match((const UNIVERSAL_CHARSTRING&)other_value.username()) : !single_value->field_username.match_omit()))return FALSE;
if(!other_value.choice().is_bound()) return FALSE;
if(!single_value->field_choice.match(other_value.choice()))return FALSE;
if(!other_value.resource().is_bound()) return FALSE;
if((other_value.resource().ispresent() ? !single_value->field_resource.match((const UNIVERSAL_CHARSTRING&)other_value.resource()) : !single_value->field_resource.match_omit()))return FALSE;
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
if (value_list.list_value[list_count].match(other_value)) return template_selection == VALUE_LIST;
return template_selection == COMPLEMENTED_LIST;
default:
TTCN_error("Matching an uninitialized/unsupported template of type @jabber_iq_auth.Query.");
}
return FALSE;
}

boolean Query_template::is_bound() const
{
if (template_selection == UNINITIALIZED_TEMPLATE && !is_ifpresent) return FALSE;
if (template_selection != SPECIFIC_VALUE) return TRUE;
if (single_value->field_username.is_omit() || single_value->field_username.is_bound()) return TRUE;
if (single_value->field_choice.is_bound()) return TRUE;
if (single_value->field_resource.is_omit() || single_value->field_resource.is_bound()) return TRUE;
return FALSE;
}

boolean Query_template::is_value() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent) return FALSE;
if (!single_value->field_username.is_omit() && !single_value->field_username.is_value()) return FALSE;
if (!single_value->field_choice.is_value()) return FALSE;
if (!single_value->field_resource.is_omit() && !single_value->field_resource.is_value()) return FALSE;
return TRUE;
}

void Query_template::clean_up()
{
switch (template_selection) {
case SPECIFIC_VALUE:
delete single_value;
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
delete [] value_list.list_value;
default:
break;
}
template_selection = UNINITIALIZED_TEMPLATE;
}

Query Query_template::valueof() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent)
TTCN_error("Performing valueof or send operation on a non-specific template of type @jabber_iq_auth.Query.");
Query ret_val;
if (single_value->field_username.is_omit()) ret_val.username() = OMIT_VALUE;
else if (single_value->field_username.is_bound()) {
ret_val.username() = single_value->field_username.valueof();
}
if (single_value->field_choice.is_bound()) {
ret_val.choice() = single_value->field_choice.valueof();
}
if (single_value->field_resource.is_omit()) ret_val.resource() = OMIT_VALUE;
else if (single_value->field_resource.is_bound()) {
ret_val.resource() = single_value->field_resource.valueof();
}
return ret_val;
}

void Query_template::set_type(template_sel template_type, unsigned int list_length)
{
if (template_type != VALUE_LIST && template_type != COMPLEMENTED_LIST)
TTCN_error("Setting an invalid list for a template of type @jabber_iq_auth.Query.");
clean_up();
set_selection(template_type);
value_list.n_values = list_length;
value_list.list_value = new Query_template[list_length];
}

Query_template& Query_template::list_item(unsigned int list_index) const
{
if (template_selection != VALUE_LIST && template_selection != COMPLEMENTED_LIST)
TTCN_error("Accessing a list element of a non-list template of type @jabber_iq_auth.Query.");
if (list_index >= value_list.n_values)
TTCN_error("Index overflow in a value list template of type @jabber_iq_auth.Query.");
return value_list.list_value[list_index];
}

UNIVERSAL_CHARSTRING_template& Query_template::username()
{
set_specific();
return single_value->field_username;
}

const UNIVERSAL_CHARSTRING_template& Query_template::username() const
{
if (template_selection != SPECIFIC_VALUE)
TTCN_error("Accessing field username of a non-specific template of type @jabber_iq_auth.Query.");
return single_value->field_username;
}

Query_choice_template& Query_template::choice()
{
set_specific();
return single_value->field_choice;
}

const Query_choice_template& Query_template::choice() const
{
if (template_selection != SPECIFIC_VALUE)
TTCN_error("Accessing field choice of a non-specific template of type @jabber_iq_auth.Query.");
return single_value->field_choice;
}

UNIVERSAL_CHARSTRING_template& Query_template::resource()
{
set_specific();
return single_value->field_resource;
}

const UNIVERSAL_CHARSTRING_template& Query_template::resource() const
{
if (template_selection != SPECIFIC_VALUE)
TTCN_error("Accessing field resource of a non-specific template of type @jabber_iq_auth.Query.");
return single_value->field_resource;
}

int Query_template::size_of() const
{
  if (is_ifpresent) TTCN_error("Performing sizeof() operation on a template of type @jabber_iq_auth.Query which has an ifpresent attribute.");
  switch (template_selection)
  {
  case SPECIFIC_VALUE:
  {    int ret_val = 1;
      if (single_value->field_username.is_present()) ret_val++;
      if (single_value->field_resource.is_present()) ret_val++;
      return ret_val;
    }
  case VALUE_LIST:
   {
     if (value_list.n_values<1)
       TTCN_error("Internal error: Performing sizeof() operation on a template of type @jabber_iq_auth.Query containing an empty list.");
      int item_size = value_list.list_value[0].size_of();
      for (unsigned int l_idx = 1; l_idx < value_list.n_values; l_idx++)
      {
        if (value_list.list_value[l_idx].size_of()!=item_size)
          TTCN_error("Performing sizeof() operation on a template of type @jabber_iq_auth.Query containing a value list with different sizes.");
      }
      return item_size;
    }
  case OMIT_VALUE:
    TTCN_error("Performing sizeof() operation on a template of type @jabber_iq_auth.Query containing omit value.");
  case ANY_VALUE:
  case ANY_OR_OMIT:
    TTCN_error("Performing sizeof() operation on a template of type @jabber_iq_auth.Query containing */? value.");
  case COMPLEMENTED_LIST:
    TTCN_error("Performing sizeof() operation on a template of type @jabber_iq_auth.Query containing complemented list.");
  default:
    TTCN_error("Performing sizeof() operation on an uninitialized/unsupported template of type @jabber_iq_auth.Query.");
  }
  return 0;
}

void Query_template::log() const
{
switch (template_selection) {
case SPECIFIC_VALUE:
TTCN_Logger::log_event_str("{ username := ");
single_value->field_username.log();
TTCN_Logger::log_event_str(", choice := ");
single_value->field_choice.log();
TTCN_Logger::log_event_str(", resource := ");
single_value->field_resource.log();
TTCN_Logger::log_event_str(" }");
break;
case COMPLEMENTED_LIST:
TTCN_Logger::log_event_str("complement ");
case VALUE_LIST:
TTCN_Logger::log_char('(');
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++) {
if (list_count > 0) TTCN_Logger::log_event_str(", ");
value_list.list_value[list_count].log();
}
TTCN_Logger::log_char(')');
break;
default:
log_generic();
}
log_ifpresent();
}

void Query_template::log_match(const Query& match_value) const
{
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
if(match(match_value)){
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str(" matched");
} else{
if (template_selection == SPECIFIC_VALUE) {
size_t previous_size = TTCN_Logger::get_logmatch_buffer_len();
if (match_value.username().ispresent()){
if(!single_value->field_username.match(match_value.username())){
TTCN_Logger::log_logmatch_info(".username");
single_value->field_username.log_match(match_value.username());
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
} else {
if (!single_value->field_username.match_omit()){
 TTCN_Logger::log_logmatch_info(".username := omit with ");
TTCN_Logger::print_logmatch_buffer();
single_value->field_username.log();
TTCN_Logger::log_event_str(" unmatched");
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
}
if(!single_value->field_choice.match(match_value.choice())){
TTCN_Logger::log_logmatch_info(".choice");
single_value->field_choice.log_match(match_value.choice());
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
if (match_value.resource().ispresent()){
if(!single_value->field_resource.match(match_value.resource())){
TTCN_Logger::log_logmatch_info(".resource");
single_value->field_resource.log_match(match_value.resource());
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
} else {
if (!single_value->field_resource.match_omit()){
 TTCN_Logger::log_logmatch_info(".resource := omit with ");
TTCN_Logger::print_logmatch_buffer();
single_value->field_resource.log();
TTCN_Logger::log_event_str(" unmatched");
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
}
}else {
TTCN_Logger::print_logmatch_buffer();
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
TTCN_Logger::log_event_str(" unmatched");
}
}
return;
}
if (template_selection == SPECIFIC_VALUE) {
TTCN_Logger::log_event_str("{ username := ");
if (match_value.username().ispresent()) single_value->field_username.log_match(match_value.username());
else {
TTCN_Logger::log_event_str("omit with ");
single_value->field_username.log();
if (single_value->field_username.match_omit()) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
TTCN_Logger::log_event_str(", choice := ");
single_value->field_choice.log_match(match_value.choice());
TTCN_Logger::log_event_str(", resource := ");
if (match_value.resource().ispresent()) single_value->field_resource.log_match(match_value.resource());
else {
TTCN_Logger::log_event_str("omit with ");
single_value->field_resource.log();
if (single_value->field_resource.match_omit()) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
TTCN_Logger::log_event_str(" }");
} else {
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
if (match(match_value)) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
}

void Query_template::encode_text(Text_Buf& text_buf) const
{
encode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
single_value->field_username.encode_text(text_buf);
single_value->field_choice.encode_text(text_buf);
single_value->field_resource.encode_text(text_buf);
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
text_buf.push_int(value_list.n_values);
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an uninitialized/unsupported template of type @jabber_iq_auth.Query.");
}
}

void Query_template::decode_text(Text_Buf& text_buf)
{
clean_up();
decode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
single_value = new single_value_struct;
single_value->field_username.decode_text(text_buf);
single_value->field_choice.decode_text(text_buf);
single_value->field_resource.decode_text(text_buf);
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = text_buf.pull_int().get_val();
value_list.list_value = new Query_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: An unknown/unsupported selection was received in a template of type @jabber_iq_auth.Query.");
}
}

void Query_template::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for record template type `@jabber_iq_auth.Query'");
    }
    if (strcmp("username", param_field) == 0) {
      username().set_param(param);
      return;
    } else if (strcmp("choice", param_field) == 0) {
      choice().set_param(param);
      return;
    } else if (strcmp("resource", param_field) == 0) {
      resource().set_param(param);
      return;
    } else param.error("Field `%s' not found in record template type `@jabber_iq_auth.Query'", param_field);
  }
  param.basic_check(Module_Param::BC_TEMPLATE, "record template");
  switch (param.get_type()) {
  case Module_Param::MP_Omit:
    *this = OMIT_VALUE;
    break;
  case Module_Param::MP_Any:
    *this = ANY_VALUE;
    break;
  case Module_Param::MP_AnyOrNone:
    *this = ANY_OR_OMIT;
    break;
  case Module_Param::MP_List_Template:
  case Module_Param::MP_ComplementList_Template:
    set_type(param.get_type()==Module_Param::MP_List_Template ? VALUE_LIST : COMPLEMENTED_LIST, param.get_size());
    for (size_t p_i=0; p_i<param.get_size(); p_i++) {
      list_item(p_i).set_param(*param.get_elem(p_i));
    }
    break;
  case Module_Param::MP_Value_List:
    if (3<param.get_size()) {
      param.error("record template of type @jabber_iq_auth.Query has 3 fields but list value has %d fields", (int)param.get_size());
    }
    if (param.get_size()>0 && param.get_elem(0)->get_type()!=Module_Param::MP_NotUsed) username().set_param(*param.get_elem(0));
    if (param.get_size()>1 && param.get_elem(1)->get_type()!=Module_Param::MP_NotUsed) choice().set_param(*param.get_elem(1));
    if (param.get_size()>2 && param.get_elem(2)->get_type()!=Module_Param::MP_NotUsed) resource().set_param(*param.get_elem(2));
    break;
  case Module_Param::MP_Assignment_List: {
    Vector<bool> value_used(param.get_size());
    value_used.resize(param.get_size(), false);
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "username")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          username().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "choice")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          choice().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "resource")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          resource().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) if (!value_used[val_idx]) {
      param.get_elem(val_idx)->error("Non existent field name in type @jabber_iq_auth.Query: %s", param.get_elem(val_idx)->get_id()->get_name());
      break;
    }
  } break;
  default:
    param.type_error("record template", "@jabber_iq_auth.Query");
  }
  is_ifpresent = param.get_ifpresent();
}

void Query_template::check_restriction(template_res t_res, const char* t_name) const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return;
switch ((t_name&&(t_res==TR_VALUE))?TR_OMIT:t_res) {
case TR_OMIT:
if (template_selection==OMIT_VALUE) return;
case TR_VALUE:
if (template_selection!=SPECIFIC_VALUE || is_ifpresent) break;
single_value->field_username.check_restriction(t_res, t_name ? t_name : "@jabber_iq_auth.Query");
single_value->field_choice.check_restriction(t_res, t_name ? t_name : "@jabber_iq_auth.Query");
single_value->field_resource.check_restriction(t_res, t_name ? t_name : "@jabber_iq_auth.Query");
return;
case TR_PRESENT:
if (!match_omit()) return;
break;
default:
return;
}
TTCN_error("Restriction `%s' on template of type %s violated.", get_res_name(t_res), t_name ? t_name : "@jabber_iq_auth.Query");
}

boolean Query_template::is_present() const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return FALSE;
return !match_omit();
}

boolean Query_template::match_omit() const
{
if (is_ifpresent) return TRUE;
switch (template_selection) {
case OMIT_VALUE:
case ANY_OR_OMIT:
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int l_idx=0; l_idx<value_list.n_values; l_idx++)
if (value_list.list_value[l_idx].match_omit())
return template_selection==VALUE_LIST;
return template_selection==COMPLEMENTED_LIST;
default:
return FALSE;
}
return FALSE;
}


/* Bodies of static functions */

static void pre_init_module()
{
XSD::module_object.pre_init_module();
}

static void post_init_module()
{
XSD::module_object.post_init_module();
}


} /* end of namespace */
