// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for user (user@user-multicom) on Wed Sep 16 13:14:39 2015

// Copyright Ericsson Telecom AB 2000-2014

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "urn_ietf_params_xml_ns_xmpp_bind.hh"

namespace urn__ietf__params__xml__ns__xmpp__bind {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const unsigned char module_checksum[] = { 0xb6, 0xc7, 0xf1, 0x3f, 0x6b, 0x44, 0x77, 0x00, 0x6c, 0x7d, 0xa7, 0x63, 0xfa, 0xda, 0xef, 0xfa };

/* Global variable definitions */

const XERdescriptor_t       Bind_choice_xer_ = { {"choice>\n", "choice>\n"}, {8, 8}, 0 |UNTAGGED, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_JSONdescriptor_t Bind_choice_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Bind_choice_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice", NULL, NULL, NULL, &Bind_choice_xer_, &Bind_choice_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       ResourceType_xer_ = { {"ResourceType>\n", "resourceType>\n"}, {14, 14}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t ResourceType_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.ResourceType", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &ResourceType_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Bind_choice_resource_xer_ = { {"resource>\n", "resource>\n"}, {10, 10}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Bind_choice_resource_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.resource", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Bind_choice_resource_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       FullJIDType_xer_ = { {"FullJIDType>\n", "fullJIDType>\n"}, {13, 13}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t FullJIDType_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.FullJIDType", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &FullJIDType_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Bind_choice_jid_xer_ = { {"jid>\n", "jid>\n"}, {5, 5}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_Typedescriptor_t Bind_choice_jid_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.jid", NULL, &UsefulTtcn3Types::utf8string_raw_, &UNIVERSAL_CHARSTRING_text_, &Bind_choice_jid_xer_, &UNIVERSAL_CHARSTRING_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
const XERdescriptor_t       Bind_xer_ = { {"Bind>\n", "bind>\n"}, {6, 6}, 0, WHITESPACE_PRESERVE,  NULL, &module_object, 14, 0, NULL, NULL };
const TTCN_JSONdescriptor_t Bind_json_ = { false, NULL, false, NULL };
const TTCN_Typedescriptor_t Bind_descr_ = { "@urn_ietf_params_xml_ns_xmpp_bind.Bind", NULL, NULL, NULL, &Bind_xer_, &Bind_json_, NULL, TTCN_Typedescriptor_t::DONTCARE };
static const size_t num_namespaces = 21;
static const namespace_t xml_namespaces[num_namespaces+1] = {
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { "urn:ietf:params:xml:ns:xmpp-bind", "tq0011" },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { NULL, NULL },
  { "http://www.w3.org/2001/XMLSchema-instance", "xsi" }
};

TTCN_Module module_object("urn_ietf_params_xml_ns_xmpp_bind", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 21LU, xml_namespaces, post_init_module, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_5,
  current_runtime_version.requires_minor_version_3,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Member functions of C++ classes */

void Bind_choice::copy_value(const Bind_choice& other_value)
{
switch (other_value.union_selection) {
case ALT_resource:
field_resource = new UNIVERSAL_CHARSTRING(*other_value.field_resource);
break;
case ALT_jid:
field_jid = new UNIVERSAL_CHARSTRING(*other_value.field_jid);
break;
default:
TTCN_error("Assignment of an unbound union value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
union_selection = other_value.union_selection;
}

Bind_choice::Bind_choice()
{
union_selection = UNBOUND_VALUE;
}

Bind_choice::Bind_choice(const Bind_choice& other_value)
: Base_Type(){
copy_value(other_value);
}

Bind_choice::~Bind_choice()
{
clean_up();
}

Bind_choice& Bind_choice::operator=(const Bind_choice& other_value)
{
if (this != &other_value) {
clean_up();
copy_value(other_value);
}
return *this;
}

boolean Bind_choice::operator==(const Bind_choice& other_value) const
{
if (union_selection == UNBOUND_VALUE) TTCN_error("The left operand of comparison is an unbound value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (other_value.union_selection == UNBOUND_VALUE) TTCN_error("The right operand of comparison is an unbound value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (union_selection != other_value.union_selection) return FALSE;
switch (union_selection) {
case ALT_resource:
return *field_resource == *other_value.field_resource;
case ALT_jid:
return *field_jid == *other_value.field_jid;
default:
return FALSE;
}
}

UNIVERSAL_CHARSTRING& Bind_choice::resource()
{
if (union_selection != ALT_resource) {
clean_up();
field_resource = new UNIVERSAL_CHARSTRING;
union_selection = ALT_resource;
}
return *field_resource;
}

const UNIVERSAL_CHARSTRING& Bind_choice::resource() const
{
if (union_selection != ALT_resource) TTCN_error("Using non-selected field resource in a value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return *field_resource;
}

UNIVERSAL_CHARSTRING& Bind_choice::jid()
{
if (union_selection != ALT_jid) {
clean_up();
field_jid = new UNIVERSAL_CHARSTRING;
union_selection = ALT_jid;
}
return *field_jid;
}

const UNIVERSAL_CHARSTRING& Bind_choice::jid() const
{
if (union_selection != ALT_jid) TTCN_error("Using non-selected field jid in a value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return *field_jid;
}

boolean Bind_choice::ischosen(union_selection_type checked_selection) const
{
if (checked_selection == UNBOUND_VALUE) TTCN_error("Internal error: Performing ischosen() operation on an invalid field of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (union_selection == UNBOUND_VALUE) TTCN_error("Performing ischosen() operation on an unbound value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return union_selection == checked_selection;
}

boolean Bind_choice::is_bound() const
{
  return union_selection != UNBOUND_VALUE;
}

boolean Bind_choice::is_value() const
{
switch (union_selection) {
case UNBOUND_VALUE: return FALSE;
case ALT_resource: return field_resource->is_value();
case ALT_jid: return field_jid->is_value();
default: TTCN_error("Invalid selection in union is_bound");}
}

void Bind_choice::clean_up()
{
switch (union_selection) {
case ALT_resource:
  delete field_resource;
  break;
case ALT_jid:
  delete field_jid;
  break;
default:
  break;
}
union_selection = UNBOUND_VALUE;
}

void Bind_choice::log() const
{
switch (union_selection) {
case ALT_resource:
TTCN_Logger::log_event_str("{ resource := ");
field_resource->log();
TTCN_Logger::log_event_str(" }");
break;
case ALT_jid:
TTCN_Logger::log_event_str("{ jid := ");
field_jid->log();
TTCN_Logger::log_event_str(" }");
break;
default:
TTCN_Logger::log_event_unbound();
}
}

void Bind_choice::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for union type `@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice'");
    }
    if (strcmp("resource", param_field) == 0) {
      resource().set_param(param);
      return;
    } else if (strcmp("jid", param_field) == 0) {
      jid().set_param(param);
      return;
    } else param.error("Field `%s' not found in union type `@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice'", param_field);
  }
  param.basic_check(Module_Param::BC_VALUE, "union value");
  if (param.get_type()==Module_Param::MP_Value_List && param.get_size()==0) return;
  if (param.get_type()!=Module_Param::MP_Assignment_List) {
    param.error("union value with field name was expected");
  }
  Module_Param* mp_last = param.get_elem(param.get_size()-1);
  if (!strcmp(mp_last->get_id()->get_name(), "resource")) {
    resource().set_param(*mp_last);
    return;
  }
  if (!strcmp(mp_last->get_id()->get_name(), "jid")) {
    jid().set_param(*mp_last);
    return;
  }
  mp_last->error("Field %s does not exist in type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.", mp_last->get_id()->get_name());
}

void Bind_choice::set_implicit_omit()
{
switch (union_selection) {
case ALT_resource:
field_resource->set_implicit_omit(); break;
case ALT_jid:
field_jid->set_implicit_omit(); break;
default: break;
}
}

void Bind_choice::encode_text(Text_Buf& text_buf) const
{
text_buf.push_int(union_selection);
switch (union_selection) {
case ALT_resource:
field_resource->encode_text(text_buf);
break;
case ALT_jid:
field_jid->encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an unbound value of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}

void Bind_choice::decode_text(Text_Buf& text_buf)
{
switch ((union_selection_type)text_buf.pull_int().get_val()) {
case ALT_resource:
resource().decode_text(text_buf);
break;
case ALT_jid:
jid().decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized union selector was received for type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}

void Bind_choice::encode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...) const
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-encoding type '%s': ", p_td.name);
    unsigned BER_coding=va_arg(pvar, unsigned);
    BER_encode_chk_coding(BER_coding);
    ASN_BER_TLV_t *tlv=BER_encode_TLV(p_td, BER_coding);
    tlv->put_in_buffer(p_buf);
    ASN_BER_TLV_t::destruct(tlv);
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-encoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    RAW_enc_tr_pos rp;
    rp.level=0;
    rp.pos=NULL;
    RAW_enc_tree root(TRUE, NULL, &rp, 1, p_td.raw);
    RAW_encode(p_td, root);
    root.put_to_buf(p_buf);
    break;}
  case TTCN_EncDec::CT_TEXT: {
    TTCN_EncDec_ErrorContext ec("While TEXT-encoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
      ("No TEXT descriptor available for type '%s'.", p_td.name);
    TEXT_encode(p_td,p_buf);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-encoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XER_encode(*(p_td.xer),p_buf, XER_coding, 0, 0);
    p_buf.put_c('\n');
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-encoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok(va_arg(pvar, int) != 0);
    JSON_encode(p_td, tok);
    p_buf.put_s(tok.get_buffer_length(), (const unsigned char*)tok.get_buffer());
    break;}
  default:
    TTCN_error("Unknown coding method requested to encode type '%s'", p_td.name);
  }
  va_end(pvar);
}

void Bind_choice::decode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...)
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-decoding type '%s': ", p_td.name);
    unsigned L_form=va_arg(pvar, unsigned);
    ASN_BER_TLV_t tlv;
    BER_decode_str2TLV(p_buf, tlv, L_form);
    BER_decode_TLV(p_td, tlv, L_form);
    if(tlv.isComplete) p_buf.increase_pos(tlv.get_len());
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-decoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    raw_order_t r_order;
    switch(p_td.raw->top_bit_order) {
    case TOP_BIT_LEFT:
      r_order=ORDER_LSB;
      break;
    case TOP_BIT_RIGHT:
    default:
      r_order=ORDER_MSB;
    }
    int rawr = RAW_decode(p_td, p_buf, p_buf.get_len()*8, r_order);
    if(rawr<0) switch (-rawr) {
    case TTCN_EncDec::ET_INCOMPL_MSG:
    case TTCN_EncDec::ET_LEN_ERR:
      ec.error((TTCN_EncDec::error_type_t)-rawr, "Can not decode type '%s', because incomplete message was received", p_td.name);
      break;
    case 1:
    default:
      ec.error(TTCN_EncDec::ET_INVAL_MSG, "Can not decode type '%s', because invalid message was received", p_td.name);
      break;
    }
    break;}
  case TTCN_EncDec::CT_TEXT: {
    Limit_Token_List limit;
    TTCN_EncDec_ErrorContext ec("While TEXT-decoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
        ("No TEXT descriptor available for type '%s'.", p_td.name);
    const unsigned char *b_data=p_buf.get_data();
    if(b_data[p_buf.get_len()-1]!='\0'){
      p_buf.set_pos(p_buf.get_len());
      p_buf.put_zero(8,ORDER_LSB);
      p_buf.rewind();
    }
    if(TEXT_decode(p_td,p_buf,limit)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-decoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XmlReaderWrap reader(p_buf);
    for (int rd_ok=reader.Read(); rd_ok==1; rd_ok=reader.Read()) {
      if (reader.NodeType() == XML_READER_TYPE_ELEMENT) break;
    }
    XER_decode(*(p_td.xer), reader, XER_coding | XER_TOPLEVEL, 0);
    size_t bytes = reader.ByteConsumed();
    p_buf.set_pos(bytes);
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-decoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok((const char*)p_buf.get_data(), p_buf.get_len());
    if(JSON_decode(p_td, tok, false)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    p_buf.set_pos(tok.get_buf_pos());
    break;}
  default:
    TTCN_error("Unknown coding method requested to decode type '%s'", p_td.name);
  }
  va_end(pvar);
}

boolean Bind_choice::can_start(const char *name, const char *uri, const XERdescriptor_t& xd, unsigned int flavor) {
  boolean exer = is_exer(flavor);
  if (!exer || (!(xd.xer_bits & UNTAGGED) && !(flavor & (USE_NIL|(exer ? XER_LIST : XER_RECOF))))) return check_name(name, xd, exer) && (!exer || (flavor & USE_TYPE_ATTR) || check_namespace(uri, xd));
  flavor &= ~XER_RECOF;
  if (UNIVERSAL_CHARSTRING::can_start(name, uri, Bind_choice_resource_xer_, flavor)) return true;
  if (UNIVERSAL_CHARSTRING::can_start(name, uri, Bind_choice_jid_xer_, flavor)) return true;
  return false;
}

char ** Bind_choice::collect_ns(const XERdescriptor_t& p_td, size_t& num, bool& def_ns) const {
  size_t num_collected;
  char **collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
  char **new_ns;
  size_t num_new;
  boolean need_type = FALSE;
  try {
    bool def_ns_1 = false;
    switch (union_selection) {
    case ALT_resource:
      new_ns = field_resource->collect_ns(Bind_choice_resource_xer_, num_new, def_ns_1);
      def_ns = def_ns || def_ns_1;
      merge_ns(collected_ns, num_collected, new_ns, num_new);
      break;
    case ALT_jid:
      new_ns = field_jid->collect_ns(Bind_choice_jid_xer_, num_new, def_ns_1);
      def_ns = def_ns || def_ns_1;
      merge_ns(collected_ns, num_collected, new_ns, num_new);
      need_type = (Bind_choice_jid_xer_.namelens[1] > 2);
      break;
    default: break;
    }
    if ((p_td.xer_bits & USE_TYPE_ATTR) && !(p_td.xer_bits & XER_ATTRIBUTE) && need_type) {
      collected_ns = (char**)Realloc(collected_ns, sizeof(char*) * ++num_collected);
      const namespace_t *c_ns = p_td.my_module->get_controlns();
      collected_ns[num_collected-1] = mprintf(" xmlns:%s='%s'", c_ns->px, c_ns->ns);
    }
  }
  catch (...) {
    while (num_collected > 0) Free(collected_ns[--num_collected]);
    Free(collected_ns);
    throw;
  }
  num = num_collected;
  return collected_ns;
}

int Bind_choice::XER_encode(const XERdescriptor_t& p_td, TTCN_Buffer& p_buf, unsigned int p_flavor, int p_indent, embed_values_enc_struct_t*) const
{
  if (UNBOUND_VALUE==union_selection) {
    TTCN_error("Attempt to XER-encode an unbound union value.");
    return 0;
  }
  TTCN_EncDec_ErrorContext ec_0("Alternative '");
  TTCN_EncDec_ErrorContext ec_1;
  int encoded_length=(int)p_buf.get_len();
  unsigned int flavor_1 = p_flavor;
  if (is_exer(p_flavor)) flavor_1 &= ~XER_RECOF;
  bool omit_tag = begin_xml(p_td, p_buf, flavor_1, p_indent, false, (collector_fn)&Bind_choice::collect_ns);
  unsigned int flavor_0 = (p_flavor & XER_MASK);
  switch (union_selection) {
  case ALT_resource:
    ec_1.set_msg("resource': ");
    field_resource->XER_encode(Bind_choice_resource_xer_, p_buf, flavor_0, p_indent + (!p_indent || !omit_tag), 0);
    break;
  case ALT_jid:
    ec_1.set_msg("jid': ");
    field_jid->XER_encode(Bind_choice_jid_xer_, p_buf, flavor_0, p_indent + (!p_indent || !omit_tag), 0);
    break;
  case UNBOUND_VALUE:
    (void)flavor_0;
    break;
  } //switch
  end_xml(p_td, p_buf, flavor_1, p_indent, 0);
  return (int)p_buf.get_len() - encoded_length;
}

int Bind_choice::XER_decode(const XERdescriptor_t& p_td, XmlReaderWrap& p_reader, unsigned int p_flavor, embed_values_dec_struct_t*)
{
  int e_xer = is_exer(p_flavor);
  int type = 0;
  int rd_ok=1, xml_depth=-1;
  int xerbits = p_td.xer_bits;
  if (p_flavor & XER_TOPLEVEL) xerbits &= ~UNTAGGED;
  if (xerbits & USE_TYPE_ATTR) p_flavor &= ~XER_RECOF;
  boolean own_tag = !(e_xer && ((xerbits & (ANY_ELEMENT | UNTAGGED)) || (p_flavor & (USE_NIL|(e_xer ? XER_LIST : XER_RECOF)))));
  if ((e_xer || !is_record_of(p_flavor)) && own_tag)
  for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_ELEMENT) {
      verify_name(p_reader, p_td, e_xer);
      xml_depth = p_reader.Depth();
      if (!(e_xer && (p_td.xer_bits & USE_TYPE_ATTR))
        && !p_reader.IsEmptyElement()) rd_ok = p_reader.Read();
      break;
    }
  }
  unsigned int flavor_1 = (p_flavor & XER_MASK);
  for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_ELEMENT) break;
    else if (type == XML_READER_TYPE_END_ELEMENT) break;
  }
  if (rd_ok) {
    TTCN_EncDec_ErrorContext ec_1("Alternative '");
    TTCN_EncDec_ErrorContext ec_2;
    const char *elem_name;
    const char *ns_uri = 0;
    {
      elem_name = (const char*)p_reader.LocalName();
      ns_uri    = (const char*)p_reader.NamespaceUri();
    }
    if (UNIVERSAL_CHARSTRING::can_start(elem_name, ns_uri, Bind_choice_resource_xer_, flavor_1) || (Bind_choice_resource_xer_.xer_bits & ANY_ELEMENT)) {
      ec_2.set_msg("resource': ");
      resource().XER_decode(Bind_choice_resource_xer_, p_reader, flavor_1, 0);
      if (!resource().is_bound()) {
        TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "Failed to decode field.");
      }
    }
    else if (UNIVERSAL_CHARSTRING::can_start(elem_name, ns_uri, Bind_choice_jid_xer_, flavor_1) || (Bind_choice_jid_xer_.xer_bits & ANY_ELEMENT)) {
      ec_2.set_msg("jid': ");
      jid().XER_decode(Bind_choice_jid_xer_, p_reader, flavor_1, 0);
      if (!jid().is_bound()) {
        TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "Failed to decode field.");
      }
    }
    else {
      ec_1.set_msg(" ");
      TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_INVAL_MSG, "'%s' does not match any alternative", elem_name);
      if (xml_depth >= 0) for (; rd_ok == 1 && p_reader.Depth() > xml_depth; rd_ok = p_reader.Read()) ;
    }
  }
  if ((e_xer || !is_record_of(p_flavor)) && own_tag)
  for (; rd_ok == 1; rd_ok = p_reader.Read()) {
    type = p_reader.NodeType();
    if (type == XML_READER_TYPE_END_ELEMENT) {
      verify_end(p_reader, p_td, xml_depth, e_xer);
      rd_ok = p_reader.Read(); // one last time
      break;
    }
  }
  return 1;
}

int Bind_choice::JSON_encode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok) const
{
  int enc_len = p_tok.put_next_token(JSON_TOKEN_OBJECT_START, NULL);

  switch(union_selection) {
  case ALT_resource:
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "resource");
    enc_len += field_resource->JSON_encode(Bind_choice_resource_descr_, p_tok);
    break;
  case ALT_jid:
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "jid");
    enc_len += field_jid->JSON_encode(Bind_choice_jid_descr_, p_tok);
    break;
  default:
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, 
      "Encoding an unbound value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
    return -1;
  }

  enc_len += p_tok.put_next_token(JSON_TOKEN_OBJECT_END, NULL);
  return enc_len;
}

int Bind_choice::JSON_decode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok, boolean p_silent)
{
  json_token_t j_token = JSON_TOKEN_NONE;
  int dec_len = p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_ERROR == j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }
  else if (JSON_TOKEN_OBJECT_START != j_token) {
    return JSON_ERROR_INVALID_TOKEN;
  }

  char* fld_name = 0;
  size_t name_len = 0;  dec_len += p_tok.get_next_token(&j_token, &fld_name, &name_len);
  if (JSON_TOKEN_NAME != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_NAME_TOKEN_ERROR);
    return JSON_ERROR_FATAL;
  } else {
    union_selection = UNBOUND_VALUE;
    if (0 == strncmp(fld_name, "resource", name_len)) {
      int ret_val = resource().JSON_decode(Bind_choice_resource_descr_, p_tok, p_silent);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "resource");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += ret_val;
      }
    } else if (0 == strncmp(fld_name, "jid", name_len)) {
      int ret_val = jid().JSON_decode(Bind_choice_jid_descr_, p_tok, p_silent);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "jid");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += ret_val;
      }
    } else {
      char* fld_name2 = mcopystrn(fld_name, name_len);
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_INVALID_NAME_ERROR, fld_name2);
      Free(fld_name2);
      return JSON_ERROR_FATAL;
    }
  }

  dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_OBJECT_END != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_STATIC_OBJECT_END_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }

  return dec_len;
}

void Bind_choice_template::copy_value(const Bind_choice& other_value)
{
single_value.union_selection = other_value.get_selection();
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
single_value.field_resource = new UNIVERSAL_CHARSTRING_template(other_value.resource());
break;
case Bind_choice::ALT_jid:
single_value.field_jid = new UNIVERSAL_CHARSTRING_template(other_value.jid());
break;
default:
TTCN_error("Initializing a template with an unbound value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
set_selection(SPECIFIC_VALUE);
}

void Bind_choice_template::copy_template(const Bind_choice_template& other_value)
{
switch (other_value.template_selection) {
case SPECIFIC_VALUE:
single_value.union_selection = other_value.single_value.union_selection;
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
single_value.field_resource = new UNIVERSAL_CHARSTRING_template(*other_value.single_value.field_resource);
break;
case Bind_choice::ALT_jid:
single_value.field_jid = new UNIVERSAL_CHARSTRING_template(*other_value.single_value.field_jid);
break;
default:
TTCN_error("Internal error: Invalid union selector in a specific value when copying a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = other_value.value_list.n_values;
value_list.list_value = new Bind_choice_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].copy_template(other_value.value_list.list_value[list_count]);
break;
default:
TTCN_error("Copying an uninitialized template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
set_selection(other_value);
}

Bind_choice_template::Bind_choice_template()
{
}

Bind_choice_template::Bind_choice_template(template_sel other_value)
 : Base_Template(other_value)
{
check_single_selection(other_value);
}

Bind_choice_template::Bind_choice_template(const Bind_choice& other_value)
{
copy_value(other_value);
}

Bind_choice_template::Bind_choice_template(const OPTIONAL<Bind_choice>& other_value)
{
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Bind_choice&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Creating a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice from an unbound optional field.");
}
}

Bind_choice_template::Bind_choice_template(const Bind_choice_template& other_value)
: Base_Template(){
copy_template(other_value);
}

Bind_choice_template::~Bind_choice_template()
{
clean_up();
}

void Bind_choice_template::clean_up()
{
switch (template_selection) {
case SPECIFIC_VALUE:
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
delete single_value.field_resource;
break;
case Bind_choice::ALT_jid:
delete single_value.field_jid;
default:
break;
}
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
delete [] value_list.list_value;
default:
break;
}
template_selection = UNINITIALIZED_TEMPLATE;
}

Bind_choice_template& Bind_choice_template::operator=(template_sel other_value)
{
check_single_selection(other_value);
clean_up();
set_selection(other_value);
return *this;
}

Bind_choice_template& Bind_choice_template::operator=(const Bind_choice& other_value)
{
clean_up();
copy_value(other_value);
return *this;
}

Bind_choice_template& Bind_choice_template::operator=(const OPTIONAL<Bind_choice>& other_value)
{
clean_up();
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Bind_choice&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Assignment of an unbound optional field to a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
return *this;
}

Bind_choice_template& Bind_choice_template::operator=(const Bind_choice_template& other_value)
{
if (&other_value != this) {
clean_up();
copy_template(other_value);
}
return *this;
}

boolean Bind_choice_template::match(const Bind_choice& other_value) const
{
if (!other_value.is_bound()) return FALSE;
switch (template_selection) {
case ANY_VALUE:
case ANY_OR_OMIT:
return TRUE;
case OMIT_VALUE:
return FALSE;
case SPECIFIC_VALUE:
{
Bind_choice::union_selection_type value_selection = other_value.get_selection();
if (value_selection == Bind_choice::UNBOUND_VALUE) return FALSE;
if (value_selection != single_value.union_selection) return FALSE;
switch (value_selection) {
case Bind_choice::ALT_resource:
return single_value.field_resource->match(other_value.resource());
case Bind_choice::ALT_jid:
return single_value.field_jid->match(other_value.jid());
default:
TTCN_error("Internal error: Invalid selector in a specific value when matching a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
if (value_list.list_value[list_count].match(other_value)) return template_selection == VALUE_LIST;
return template_selection == COMPLEMENTED_LIST;
default:
TTCN_error ("Matching an uninitialized template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
return FALSE;
}

boolean Bind_choice_template::is_value() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent) return false;
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
return single_value.field_resource->is_value();
case Bind_choice::ALT_jid:
return single_value.field_jid->is_value();
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing is_value operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}

Bind_choice Bind_choice_template::valueof() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent)
TTCN_error("Performing valueof or send operation on a non-specific template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
Bind_choice ret_val;
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
ret_val.resource() = single_value.field_resource->valueof();
break;
case Bind_choice::ALT_jid:
ret_val.jid() = single_value.field_jid->valueof();
break;
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing valueof operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
return ret_val;
}

Bind_choice_template& Bind_choice_template::list_item(unsigned int list_index) const
{
if (template_selection != VALUE_LIST && template_selection != COMPLEMENTED_LIST) TTCN_error("Internal error: Accessing a list element of a non-list template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (list_index >= value_list.n_values) TTCN_error("Internal error: Index overflow in a value list template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return value_list.list_value[list_index];
}
void Bind_choice_template::set_type(template_sel template_type, unsigned int list_length)
{
if (template_type != VALUE_LIST && template_type != COMPLEMENTED_LIST) TTCN_error ("Internal error: Setting an invalid list for a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
clean_up();
set_selection(template_type);
value_list.n_values = list_length;
value_list.list_value = new Bind_choice_template[list_length];
}

UNIVERSAL_CHARSTRING_template& Bind_choice_template::resource()
{
if (template_selection != SPECIFIC_VALUE || single_value.union_selection != Bind_choice::ALT_resource) {
template_sel old_selection = template_selection;
clean_up();
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) single_value.field_resource = new UNIVERSAL_CHARSTRING_template(ANY_VALUE);
else single_value.field_resource = new UNIVERSAL_CHARSTRING_template;
single_value.union_selection = Bind_choice::ALT_resource;
set_selection(SPECIFIC_VALUE);
}
return *single_value.field_resource;
}

const UNIVERSAL_CHARSTRING_template& Bind_choice_template::resource() const
{
if (template_selection != SPECIFIC_VALUE) TTCN_error("Accessing field resource in a non-specific template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (single_value.union_selection != Bind_choice::ALT_resource) TTCN_error("Accessing non-selected field resource in a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return *single_value.field_resource;
}

UNIVERSAL_CHARSTRING_template& Bind_choice_template::jid()
{
if (template_selection != SPECIFIC_VALUE || single_value.union_selection != Bind_choice::ALT_jid) {
template_sel old_selection = template_selection;
clean_up();
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) single_value.field_jid = new UNIVERSAL_CHARSTRING_template(ANY_VALUE);
else single_value.field_jid = new UNIVERSAL_CHARSTRING_template;
single_value.union_selection = Bind_choice::ALT_jid;
set_selection(SPECIFIC_VALUE);
}
return *single_value.field_jid;
}

const UNIVERSAL_CHARSTRING_template& Bind_choice_template::jid() const
{
if (template_selection != SPECIFIC_VALUE) TTCN_error("Accessing field jid in a non-specific template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
if (single_value.union_selection != Bind_choice::ALT_jid) TTCN_error("Accessing non-selected field jid in a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return *single_value.field_jid;
}

boolean Bind_choice_template::ischosen(Bind_choice::union_selection_type checked_selection) const
{
if (checked_selection == Bind_choice::UNBOUND_VALUE) TTCN_error("Internal error: Performing ischosen() operation on an invalid field of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
switch (template_selection) {
case SPECIFIC_VALUE:
if (single_value.union_selection == Bind_choice::UNBOUND_VALUE) TTCN_error("Internal error: Invalid selector in a specific value when performing ischosen() operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
return single_value.union_selection == checked_selection;
case VALUE_LIST:
{
if (value_list.n_values < 1)
TTCN_error("Internal error: Performing ischosen() operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice containing an empty list.");
boolean ret_val = value_list.list_value[0].ischosen(checked_selection);
boolean all_same = TRUE;
for (unsigned int list_count = 1; list_count < value_list.n_values; list_count++) {
if (value_list.list_value[list_count].ischosen(checked_selection) != ret_val) {
all_same = FALSE;
break;
}
}
if (all_same) return ret_val;
}
case ANY_VALUE:
case ANY_OR_OMIT:
case OMIT_VALUE:
case COMPLEMENTED_LIST:
TTCN_error("Performing ischosen() operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice, which does not determine unambiguously the chosen field of the matching values.");
default:
TTCN_error("Performing ischosen() operation on an uninitialized template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
}
return FALSE;
}

void Bind_choice_template::log() const
{
switch (template_selection) {
case SPECIFIC_VALUE:
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
TTCN_Logger::log_event_str("{ resource := ");
single_value.field_resource->log();
TTCN_Logger::log_event_str(" }");
break;
case Bind_choice::ALT_jid:
TTCN_Logger::log_event_str("{ jid := ");
single_value.field_jid->log();
TTCN_Logger::log_event_str(" }");
break;
default:
TTCN_Logger::log_event_str("<invalid selector>");
}
break;
case COMPLEMENTED_LIST:
TTCN_Logger::log_event_str("complement ");
case VALUE_LIST:
TTCN_Logger::log_char('(');
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++) {
if (list_count > 0) TTCN_Logger::log_event_str(", ");
value_list.list_value[list_count].log();
}
TTCN_Logger::log_char(')');
break;
default:
log_generic();
}
log_ifpresent();
}

void Bind_choice_template::log_match(const Bind_choice& match_value) const
{
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity() && match(match_value)){
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str(" matched");
return;
}
if (template_selection == SPECIFIC_VALUE && single_value.union_selection == match_value.get_selection()) {
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
TTCN_Logger::log_logmatch_info(".resource");
single_value.field_resource->log_match(match_value.resource());
} else {
TTCN_Logger::log_event_str("{ resource := ");
single_value.field_resource->log_match(match_value.resource());
TTCN_Logger::log_event_str(" }");
}
break;
case Bind_choice::ALT_jid:
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
TTCN_Logger::log_logmatch_info(".jid");
single_value.field_jid->log_match(match_value.jid());
} else {
TTCN_Logger::log_event_str("{ jid := ");
single_value.field_jid->log_match(match_value.jid());
TTCN_Logger::log_event_str(" }");
}
break;
default:
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str("<invalid selector>");
}
} else {
TTCN_Logger::print_logmatch_buffer();
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
if (match(match_value)) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
}

void Bind_choice_template::encode_text(Text_Buf& text_buf) const
{
encode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
text_buf.push_int(single_value.union_selection);
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
single_value.field_resource->encode_text(text_buf);
break;
case Bind_choice::ALT_jid:
single_value.field_jid->encode_text(text_buf);
break;
default:
TTCN_error("Internal error: Invalid selector in a specific value when encoding a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
text_buf.push_int(value_list.n_values);
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an uninitialized template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}

void Bind_choice_template::decode_text(Text_Buf& text_buf)
{
clean_up();
decode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
{
single_value.union_selection = Bind_choice::UNBOUND_VALUE;
Bind_choice::union_selection_type new_selection = (Bind_choice::union_selection_type)text_buf.pull_int().get_val();
switch (new_selection) {
case Bind_choice::ALT_resource:
single_value.field_resource = new UNIVERSAL_CHARSTRING_template;
single_value.field_resource->decode_text(text_buf);
break;
case Bind_choice::ALT_jid:
single_value.field_jid = new UNIVERSAL_CHARSTRING_template;
single_value.field_jid->decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized union selector was received for a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
single_value.union_selection = new_selection;
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = text_buf.pull_int().get_val();
value_list.list_value = new Bind_choice_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: Unrecognized selector was received in a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
}

boolean Bind_choice_template::is_present() const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return FALSE;
return !match_omit();
}

boolean Bind_choice_template::match_omit() const
{
if (is_ifpresent) return TRUE;
switch (template_selection) {
case OMIT_VALUE:
case ANY_OR_OMIT:
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int v_idx=0; v_idx<value_list.n_values; v_idx++)
if (value_list.list_value[v_idx].match_omit())
return template_selection==VALUE_LIST;
return template_selection==COMPLEMENTED_LIST;
default:
return FALSE;
}
return FALSE;
}

void Bind_choice_template::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for union template type `@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice'");
    }
    if (strcmp("resource", param_field) == 0) {
      resource().set_param(param);
      return;
    } else if (strcmp("jid", param_field) == 0) {
      jid().set_param(param);
      return;
    } else param.error("Field `%s' not found in union template type `@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice'", param_field);
  }
  param.basic_check(Module_Param::BC_TEMPLATE, "union template");
  switch (param.get_type()) {
  case Module_Param::MP_Omit:
    *this = OMIT_VALUE;
    break;
  case Module_Param::MP_Any:
    *this = ANY_VALUE;
    break;
  case Module_Param::MP_AnyOrNone:
    *this = ANY_OR_OMIT;
    break;
  case Module_Param::MP_List_Template:
  case Module_Param::MP_ComplementList_Template:
    set_type(param.get_type()==Module_Param::MP_List_Template ? VALUE_LIST : COMPLEMENTED_LIST, param.get_size());
    for (size_t p_i=0; p_i<param.get_size(); p_i++) {
      list_item(p_i).set_param(*param.get_elem(p_i));
    }
    break;
  case Module_Param::MP_Value_List:
    if (param.get_size()==0) break;
    param.type_error("union template", "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
    break;
  case Module_Param::MP_Assignment_List: {
    Module_Param* mp_last = param.get_elem(param.get_size()-1);
    if (!strcmp(mp_last->get_id()->get_name(), "resource")) {
      resource().set_param(*mp_last);
      break;
    }
    if (!strcmp(mp_last->get_id()->get_name(), "jid")) {
      jid().set_param(*mp_last);
      break;
    }
    mp_last->error("Field %s does not exist in type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.", mp_last->get_id()->get_name());
  } break;
  default:
    param.type_error("union template", "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
  }
  is_ifpresent = param.get_ifpresent();
}

void Bind_choice_template::check_restriction(template_res t_res, const char* t_name) const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return;
switch ((t_name&&(t_res==TR_VALUE))?TR_OMIT:t_res) {
case TR_OMIT:
if (template_selection==OMIT_VALUE) return;
case TR_VALUE:
if (template_selection!=SPECIFIC_VALUE || is_ifpresent) break;
switch (single_value.union_selection) {
case Bind_choice::ALT_resource:
single_value.field_resource->check_restriction(t_res, t_name ? t_name : "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
return;
case Bind_choice::ALT_jid:
single_value.field_jid->check_restriction(t_res, t_name ? t_name : "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
return;
default:
TTCN_error("Internal error: Invalid selector in a specific value when performing check_restriction operation on a template of union type @urn_ietf_params_xml_ns_xmpp_bind.Bind.choice.");
}
case TR_PRESENT:
if (!match_omit()) return;
break;
default:
return;
}
TTCN_error("Restriction `%s' on template of type %s violated.", get_res_name(t_res), t_name ? t_name : "@urn_ietf_params_xml_ns_xmpp_bind.Bind.choice");
}

Bind::Bind()
{
  bound_flag = FALSE;
}

Bind::Bind(const Bind_choice& par_choice)
  :   field_choice(par_choice)
{
  bound_flag = TRUE;
}

Bind::Bind(const Bind& other_value)
{
if(!other_value.is_bound()) TTCN_error("Copying an unbound value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
bound_flag = TRUE;
if (other_value.choice().is_bound()) field_choice = other_value.choice();
else field_choice.clean_up();
}

void Bind::clean_up()
{
field_choice.clean_up();
bound_flag = FALSE;
}

Bind& Bind::operator=(const Bind& other_value)
{
if (this != &other_value) {
  if(!other_value.is_bound()) TTCN_error("Assignment of an unbound value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
  bound_flag = TRUE;
  if (other_value.choice().is_bound()) field_choice = other_value.choice();
  else field_choice.clean_up();
}
return *this;
}

boolean Bind::operator==(const Bind& other_value) const
{
if (!is_bound() && !other_value.is_bound()) return TRUE;
return field_choice==other_value.field_choice;
}

boolean Bind::is_bound() const
{
if (bound_flag) return TRUE;
if(field_choice.is_bound()) return TRUE;
return FALSE;
}
boolean Bind::is_value() const
{
if (!is_bound()) return FALSE;
if(!field_choice.is_value()) return FALSE;
return TRUE;
}
int Bind::size_of() const
{
  if (!is_bound()) TTCN_error("Calculating the size of an unbound record/set value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind");
  return 1;
}

void Bind::log() const
{
if (!is_bound()) {
TTCN_Logger::log_event_unbound();
return;
}
TTCN_Logger::log_event_str("{ choice := ");
field_choice.log();
TTCN_Logger::log_event_str(" }");
}

void Bind::set_param(Module_Param& param)
{
  bound_flag = TRUE;
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for record type `@urn_ietf_params_xml_ns_xmpp_bind.Bind'");
    }
    if (strcmp("choice", param_field) == 0) {
      choice().set_param(param);
      return;
    } else param.error("Field `%s' not found in record type `@urn_ietf_params_xml_ns_xmpp_bind.Bind'", param_field);
  }
  param.basic_check(Module_Param::BC_VALUE, "record value");
  switch (param.get_type()) {
  case Module_Param::MP_Value_List:
    if (1<param.get_size()) {
      param.error("record value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind has 1 fields but list value has %d fields", (int)param.get_size());
    }
    if (param.get_size()>0 && param.get_elem(0)->get_type()!=Module_Param::MP_NotUsed) choice().set_param(*param.get_elem(0));
    break;
  case Module_Param::MP_Assignment_List: {
    Vector<bool> value_used(param.get_size());
    value_used.resize(param.get_size(), false);
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "choice")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          choice().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) if (!value_used[val_idx]) {
      param.get_elem(val_idx)->error("Non existent field name in type @urn_ietf_params_xml_ns_xmpp_bind.Bind: %s", param.get_elem(val_idx)->get_id()->get_name());
      break;
    }
  } break;
  default:
    param.type_error("record value", "@urn_ietf_params_xml_ns_xmpp_bind.Bind");
  }
}

void Bind::set_implicit_omit()
{
if (choice().is_bound()) choice().set_implicit_omit();
}

void Bind::encode_text(Text_Buf& text_buf) const
{
if (!is_bound()) TTCN_error("Text encoder: Encoding an unbound record/set value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
field_choice.encode_text(text_buf);
}

void Bind::decode_text(Text_Buf& text_buf)
{
bound_flag = TRUE;
field_choice.decode_text(text_buf);
}

void Bind::encode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...) const
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-encoding type '%s': ", p_td.name);
    unsigned BER_coding=va_arg(pvar, unsigned);
    BER_encode_chk_coding(BER_coding);
    ASN_BER_TLV_t *tlv=BER_encode_TLV(p_td, BER_coding);
    tlv->put_in_buffer(p_buf);
    ASN_BER_TLV_t::destruct(tlv);
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-encoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    RAW_enc_tr_pos rp;
    rp.level=0;
    rp.pos=NULL;
    RAW_enc_tree root(FALSE, NULL, &rp, 1, p_td.raw);
    RAW_encode(p_td, root);
    root.put_to_buf(p_buf);
    break;}
  case TTCN_EncDec::CT_TEXT: {
    TTCN_EncDec_ErrorContext ec("While TEXT-encoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
      ("No TEXT descriptor available for type '%s'.", p_td.name);
    TEXT_encode(p_td,p_buf);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-encoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XER_encode(*(p_td.xer),p_buf, XER_coding, 0, 0);
    p_buf.put_c('\n');
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-encoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok(va_arg(pvar, int) != 0);
    JSON_encode(p_td, tok);
    p_buf.put_s(tok.get_buffer_length(), (const unsigned char*)tok.get_buffer());
    break;}
  default:
    TTCN_error("Unknown coding method requested to encode type '%s'", p_td.name);
  }
  va_end(pvar);
}

void Bind::decode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, TTCN_EncDec::coding_t p_coding, ...)
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-decoding type '%s': ", p_td.name);
    unsigned L_form=va_arg(pvar, unsigned);
    ASN_BER_TLV_t tlv;
    BER_decode_str2TLV(p_buf, tlv, L_form);
    BER_decode_TLV(p_td, tlv, L_form);
    if(tlv.isComplete) p_buf.increase_pos(tlv.get_len());
    break;}
  case TTCN_EncDec::CT_RAW: {
    TTCN_EncDec_ErrorContext ec("While RAW-decoding type '%s': ", p_td.name);
    if(!p_td.raw)
      TTCN_EncDec_ErrorContext::error_internal
        ("No RAW descriptor available for type '%s'.", p_td.name);
    raw_order_t r_order;
    switch(p_td.raw->top_bit_order) {
    case TOP_BIT_LEFT:
      r_order=ORDER_LSB;
      break;
    case TOP_BIT_RIGHT:
    default:
      r_order=ORDER_MSB;
    }
    int rawr = RAW_decode(p_td, p_buf, p_buf.get_len()*8, r_order);
    if(rawr<0) switch (-rawr) {
    case TTCN_EncDec::ET_INCOMPL_MSG:
    case TTCN_EncDec::ET_LEN_ERR:
      ec.error((TTCN_EncDec::error_type_t)-rawr, "Can not decode type '%s', because incomplete message was received", p_td.name);
      break;
    case 1:
    default:
      ec.error(TTCN_EncDec::ET_INVAL_MSG, "Can not decode type '%s', because invalid message was received", p_td.name);
      break;
    }
    break;}
  case TTCN_EncDec::CT_TEXT: {
    Limit_Token_List limit;
    TTCN_EncDec_ErrorContext ec("While TEXT-decoding type '%s': ", p_td.name);
    if(!p_td.text)
      TTCN_EncDec_ErrorContext::error_internal
        ("No TEXT descriptor available for type '%s'.", p_td.name);
    const unsigned char *b_data=p_buf.get_data();
    if(b_data[p_buf.get_len()-1]!='\0'){
      p_buf.set_pos(p_buf.get_len());
      p_buf.put_zero(8,ORDER_LSB);
      p_buf.rewind();
    }
    if(TEXT_decode(p_td,p_buf,limit)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    break;}
  case TTCN_EncDec::CT_XER: {
    TTCN_EncDec_ErrorContext ec("While XER-decoding type '%s': ", p_td.name);
    unsigned XER_coding=va_arg(pvar, unsigned);
    XER_encode_chk_coding(XER_coding, p_td);
    XmlReaderWrap reader(p_buf);
    for (int rd_ok=reader.Read(); rd_ok==1; rd_ok=reader.Read()) {
      if (reader.NodeType() == XML_READER_TYPE_ELEMENT) break;
    }
    XER_decode(*(p_td.xer), reader, XER_coding | XER_TOPLEVEL, 0);
    size_t bytes = reader.ByteConsumed();
    p_buf.set_pos(bytes);
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-decoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok((const char*)p_buf.get_data(), p_buf.get_len());
    if(JSON_decode(p_td, tok, false)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    p_buf.set_pos(tok.get_buf_pos());
    break;}
  default:
    TTCN_error("Unknown coding method requested to decode type '%s'", p_td.name);
  }
  va_end(pvar);
}

char ** Bind::collect_ns(const XERdescriptor_t& p_td, size_t& num_ns, bool& def_ns) const {
  size_t num_collected;
  char **collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
  try {
  char **new_ns;
  size_t num_new;
  bool def_ns_1 = false;
  new_ns = field_choice.collect_ns(Bind_choice_xer_, num_new, def_ns);
  merge_ns(collected_ns, num_collected, new_ns, num_new);
  def_ns = def_ns || def_ns_1;
  }
  catch (...) {
    while (num_collected > 0) Free(collected_ns[--num_collected]);
    Free(collected_ns);
    throw;
  }
  num_ns = num_collected;
  return collected_ns;
}

boolean Bind::can_start(const char *name, const char *uri, const XERdescriptor_t& xd, unsigned int flavor) {
  boolean e_xer = is_exer(flavor &= ~XER_RECOF);
  if (!e_xer || !((xd.xer_bits & UNTAGGED) || (flavor & (USE_NIL|XER_RECOF)))) return check_name(name, xd, e_xer) && (!e_xer || check_namespace(uri, xd));
  else if (Bind_choice::can_start(name, uri, Bind_choice_xer_, flavor)) return true;
  return false;
}

int Bind::XER_encode(const XERdescriptor_t& p_td, TTCN_Buffer& p_buf, unsigned int p_flavor, int p_indent, embed_values_enc_struct_t*) const
{
  if (!is_bound()) TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, "Encoding an unbound value.");
  TTCN_EncDec_ErrorContext ec_0("Component '");
  TTCN_EncDec_ErrorContext ec_1;
  int encoded_length=(int)p_buf.get_len();
  int e_xer = is_exer(p_flavor);
  const boolean omit_tag = e_xer && p_indent && ((p_td.xer_bits & (UNTAGGED|XER_ATTRIBUTE)) || (p_flavor & (USE_NIL|USE_TYPE_ATTR)));
  if (e_xer && (p_td.xer_bits & EMBED_VALUES)) p_flavor |= XER_CANONICAL;
  int is_indented = !is_canonical(p_flavor);
  const boolean need_control_ns = (p_td.xer_bits & (USE_NIL));
  size_t num_collected = 0;
  char **collected_ns = NULL;
  bool def_ns = false;
  if (e_xer) {
    if (p_indent == 0) {
      collected_ns = collect_ns(p_td, num_collected, def_ns);
    }
    else if ((p_flavor & DEF_NS_SQUASHED) && p_td.my_module && p_td.ns_index != -1){
      const namespace_t * ns = p_td.my_module->get_ns(p_td.ns_index);
      if (*ns->px == '\0') {
        collected_ns = Base_Type::collect_ns(p_td, num_collected, def_ns);
      }
    }
  }
  const boolean empty_ns_hack = e_xer && !omit_tag && (p_indent > 0)
    && (p_td.xer_bits & FORM_UNQUALIFIED)
    && p_td.my_module && p_td.ns_index != -1
    && *p_td.my_module->get_ns(p_td.ns_index)->px == '\0';
  const boolean delay_close = e_xer && (need_control_ns || num_collected || empty_ns_hack);
  size_t chopped_chars = 0;
  if (!omit_tag) {
    if (is_indented) do_indent(p_buf, p_indent);
    p_buf.put_c('<');
    if (e_xer) write_ns_prefix(p_td, p_buf);
    p_buf.put_s((size_t)p_td.namelens[e_xer]-(delay_close || (e_xer && (p_td.xer_bits & HAS_1UNTAGGED)))-(!is_indented || delay_close), (cbyte*)p_td.names[e_xer]);
  }
  else if (p_flavor & USE_TYPE_ATTR) {
    size_t buf_len = p_buf.get_len();
    const unsigned char * const buf_data = p_buf.get_data();
    if (buf_data[buf_len-1-chopped_chars] == '\n') ++chopped_chars;
    if (buf_data[buf_len-1-chopped_chars] == '>' ) ++chopped_chars;
    if (chopped_chars) {
      p_buf.increase_length(-chopped_chars);
    }
  }
  int sub_len=0;
  p_flavor &= XER_MASK;
  { // !QN
  if (e_xer && num_collected) {
    size_t num_ns;
    for (num_ns = 0; num_ns < num_collected; ++num_ns) {
      p_buf.put_s(strlen(collected_ns[num_ns]), (cbyte*)collected_ns[num_ns]);
      Free(collected_ns[num_ns]);
    }
    Free(collected_ns);
  }

  if (def_ns) {
    p_flavor &= ~DEF_NS_SQUASHED;
    p_flavor |=  DEF_NS_PRESENT;
  }
  else if (empty_ns_hack) {
    p_buf.put_s(9, (cbyte*)" xmlns=''");
    p_flavor &= ~DEF_NS_PRESENT;
    p_flavor |=  DEF_NS_SQUASHED;
  }
  if (delay_close && (!omit_tag || chopped_chars)) p_buf.put_s(1+is_indented, (cbyte*)">\n");
  ec_1.set_msg("choice': ");
  sub_len += field_choice.XER_encode(Bind_choice_xer_, p_buf, p_flavor, p_indent+!omit_tag, 0);
  } // QN?
  if (!omit_tag) {
  if (sub_len) {
    if (is_indented && !(e_xer && (p_td.xer_bits & (HAS_1UNTAGGED | USE_QNAME)))) {
      switch ((int)(e_xer && (p_td.xer_bits & USE_NIL))) {
      case 1: {
        const unsigned char *buf_end = p_buf.get_data() + (p_buf.get_len()-1);
        if (buf_end[-1] != '>' || *buf_end != '\n') break;
      }
      case 0:
        do_indent(p_buf, p_indent);
        break;
      }
    }
    p_buf.put_c('<');
    p_buf.put_c('/');
    if (e_xer) write_ns_prefix(p_td, p_buf);
    p_buf.put_s((size_t)p_td.namelens[e_xer]-!is_indented, (cbyte*)p_td.names[e_xer]);
  } else {
    p_buf.increase_length(-is_indented-1);
    p_buf.put_s((size_t)2+is_indented, (cbyte*)"/>\n");
  }}
  return (int)p_buf.get_len() - encoded_length;
}

int Bind::XER_decode(const XERdescriptor_t& p_td, XmlReaderWrap& p_reader, unsigned int p_flavor, embed_values_dec_struct_t*)
{
  bound_flag = TRUE;
  int e_xer = is_exer(p_flavor);
  int xerbits = p_td.xer_bits;
  if (p_flavor & XER_TOPLEVEL) xerbits &= ~UNTAGGED;
  const boolean omit_tag = e_xer && ((xerbits & (UNTAGGED|XER_ATTRIBUTE)) || (p_flavor & (USE_NIL|USE_TYPE_ATTR)));
  boolean tag_closed = (p_flavor & PARENT_CLOSED) != 0;
  const boolean parent_tag = e_xer && (p_flavor & (USE_TYPE_ATTR));
  (void)parent_tag;
  p_flavor &= XER_MASK;
  int rd_ok, xml_depth=-1, type;
  {
  TTCN_EncDec_ErrorContext ec_0("Component '");
  TTCN_EncDec_ErrorContext ec_1;
  if (!omit_tag) for (rd_ok=p_reader.Ok(); rd_ok==1; rd_ok=p_reader.Read()) {
    type = p_reader.NodeType();
    if (type==XML_READER_TYPE_ELEMENT) {
      verify_name(p_reader, p_td, e_xer);
      xml_depth = p_reader.Depth();
      tag_closed = p_reader.IsEmptyElement();
      break;
    }
  }
  if ((!omit_tag || parent_tag) && !p_reader.IsEmptyElement()) rd_ok = p_reader.Read();
  if (e_xer && p_td.dfeValue && p_reader.IsEmptyElement()) {
    field_choice = *static_cast<const Bind_choice*>(p_td.dfeValue);
  }
  else  {
    ec_1.set_msg("choice': ");
    field_choice.XER_decode(Bind_choice_xer_, p_reader, p_flavor | (p_td.xer_bits & USE_NIL)| (tag_closed ? PARENT_CLOSED : 0), 0);
  }
  } // errorcontext
  if (!omit_tag) {
    int current_depth;
    for (rd_ok = p_reader.Ok(); rd_ok == 1; rd_ok = p_reader.Read()) {
      type = p_reader.NodeType();
      if ((current_depth = p_reader.Depth()) > xml_depth) {
        if (XML_READER_TYPE_ELEMENT == type) {
          TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_TAG,
              "Unprocessed XML tag `%s'", (const char *)p_reader.Name());
        }
        continue;
      }
      else if (current_depth == xml_depth) {
        if (XML_READER_TYPE_ELEMENT == type) {
          verify_name(p_reader, p_td, e_xer);
          if (p_reader.IsEmptyElement()) {
            p_reader.Read();
            break;
          }
        }
        else if (XML_READER_TYPE_END_ELEMENT == type) {
          verify_end(p_reader, p_td, xml_depth, e_xer);
          rd_ok = p_reader.Read();
          break;
        }
      }
      else break;    }
  }
  return 1;
}

int Bind::JSON_encode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok) const
{
  if (!is_bound()) {
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND,
      "Encoding an unbound value of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
    return -1;
  }

  int enc_len = p_tok.put_next_token(JSON_TOKEN_OBJECT_START, NULL);

  {
    enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "choice");
    enc_len += field_choice.JSON_encode(Bind_choice_descr_, p_tok);
  }

  enc_len += p_tok.put_next_token(JSON_TOKEN_OBJECT_END, NULL);
  return enc_len;
}

int Bind::JSON_decode(const TTCN_Typedescriptor_t&, JSON_Tokenizer& p_tok, boolean p_silent)
{
  json_token_t j_token = JSON_TOKEN_NONE;
  int dec_len = p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_ERROR == j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }
  else if (JSON_TOKEN_OBJECT_START != j_token) {
    return JSON_ERROR_INVALID_TOKEN;
  }
  bound_flag = TRUE;

  while (true) {
    char* fld_name = 0;
    size_t name_len = 0;
    size_t buf_pos = p_tok.get_buf_pos();
    dec_len += p_tok.get_next_token(&j_token, &fld_name, &name_len);
    if (JSON_TOKEN_ERROR == j_token) {
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_NAME_TOKEN_ERROR);
      return JSON_ERROR_FATAL;
    }
    else if (JSON_TOKEN_NAME != j_token) {
      p_tok.set_buf_pos(buf_pos);
      break;
    }
    else {
      if (6 == name_len && 0 == strncmp(fld_name, "choice", name_len)) {
        int ret_val = field_choice.JSON_decode(Bind_choice_descr_, p_tok, p_silent);
        if (0 > ret_val) {
          if (JSON_ERROR_INVALID_TOKEN) {
            JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, "choice");
          }
          return JSON_ERROR_FATAL;
        }
        dec_len += ret_val;
      } else {
        char* fld_name2 = mcopystrn(fld_name, name_len);
        JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_INVALID_NAME_ERROR, fld_name2);
        dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
        if (JSON_TOKEN_NUMBER != j_token && JSON_TOKEN_STRING != j_token &&
            JSON_TOKEN_LITERAL_TRUE != j_token && JSON_TOKEN_LITERAL_FALSE != j_token &&
            JSON_TOKEN_LITERAL_NULL != j_token) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, fld_name2);
          Free(fld_name2);
          return JSON_ERROR_FATAL;
        }
        Free(fld_name2);
      }
    }
  }

  dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_OBJECT_END != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_OBJECT_END_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }

  if (!field_choice.is_bound()) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_MISSING_FIELD_ERROR, "choice");
    return JSON_ERROR_FATAL;
  }

  return dec_len;
}

struct Bind_template::single_value_struct {
Bind_choice_template field_choice;
};

void Bind_template::set_specific()
{
if (template_selection != SPECIFIC_VALUE) {
template_sel old_selection = template_selection;
clean_up();
single_value = new single_value_struct;
set_selection(SPECIFIC_VALUE);
if (old_selection == ANY_VALUE || old_selection == ANY_OR_OMIT) {
single_value->field_choice = ANY_VALUE;
}
}
}

void Bind_template::copy_value(const Bind& other_value)
{
single_value = new single_value_struct;
if (other_value.choice().is_bound()) {
  single_value->field_choice = other_value.choice();
} else {
  single_value->field_choice.clean_up();
}
set_selection(SPECIFIC_VALUE);
}

void Bind_template::copy_template(const Bind_template& other_value)
{
switch (other_value.template_selection) {
case SPECIFIC_VALUE:
single_value = new single_value_struct;
if (UNINITIALIZED_TEMPLATE != other_value.choice().get_selection()) {
single_value->field_choice = other_value.choice();
} else {
single_value->field_choice.clean_up();
}
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = other_value.value_list.n_values;
value_list.list_value = new Bind_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].copy_template(other_value.value_list.list_value[list_count]);
break;
default:
TTCN_error("Copying an uninitialized/unsupported template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
break;
}
set_selection(other_value);
}

Bind_template::Bind_template()
{
}

Bind_template::Bind_template(template_sel other_value)
 : Base_Template(other_value)
{
check_single_selection(other_value);
}

Bind_template::Bind_template(const Bind& other_value)
{
copy_value(other_value);
}

Bind_template::Bind_template(const OPTIONAL<Bind>& other_value)
{
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Bind&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Creating a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind from an unbound optional field.");
}
}

Bind_template::Bind_template(const Bind_template& other_value)
: Base_Template()
{
copy_template(other_value);
}

Bind_template::~Bind_template()
{
clean_up();
}

Bind_template& Bind_template::operator=(template_sel other_value)
{
check_single_selection(other_value);
clean_up();
set_selection(other_value);
return *this;
}

Bind_template& Bind_template::operator=(const Bind& other_value)
{
clean_up();
copy_value(other_value);
return *this;
}

Bind_template& Bind_template::operator=(const OPTIONAL<Bind>& other_value)
{
clean_up();
switch (other_value.get_selection()) {
case OPTIONAL_PRESENT:
copy_value((const Bind&)other_value);
break;
case OPTIONAL_OMIT:
set_selection(OMIT_VALUE);
break;
default:
TTCN_error("Assignment of an unbound optional field to a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
}
return *this;
}

Bind_template& Bind_template::operator=(const Bind_template& other_value)
{
if (&other_value != this) {
clean_up();
copy_template(other_value);
}
return *this;
}

boolean Bind_template::match(const Bind& other_value) const
{
if (!other_value.is_bound()) return FALSE;
switch (template_selection) {
case ANY_VALUE:
case ANY_OR_OMIT:
return TRUE;
case OMIT_VALUE:
return FALSE;
case SPECIFIC_VALUE:
if(!other_value.choice().is_bound()) return FALSE;
if(!single_value->field_choice.match(other_value.choice()))return FALSE;
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
if (value_list.list_value[list_count].match(other_value)) return template_selection == VALUE_LIST;
return template_selection == COMPLEMENTED_LIST;
default:
TTCN_error("Matching an uninitialized/unsupported template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
}
return FALSE;
}

boolean Bind_template::is_bound() const
{
if (template_selection == UNINITIALIZED_TEMPLATE && !is_ifpresent) return FALSE;
if (template_selection != SPECIFIC_VALUE) return TRUE;
if (single_value->field_choice.is_bound()) return TRUE;
return FALSE;
}

boolean Bind_template::is_value() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent) return FALSE;
if (!single_value->field_choice.is_value()) return FALSE;
return TRUE;
}

void Bind_template::clean_up()
{
switch (template_selection) {
case SPECIFIC_VALUE:
delete single_value;
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
delete [] value_list.list_value;
default:
break;
}
template_selection = UNINITIALIZED_TEMPLATE;
}

Bind Bind_template::valueof() const
{
if (template_selection != SPECIFIC_VALUE || is_ifpresent)
TTCN_error("Performing valueof or send operation on a non-specific template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
Bind ret_val;
if (single_value->field_choice.is_bound()) {
ret_val.choice() = single_value->field_choice.valueof();
}
return ret_val;
}

void Bind_template::set_type(template_sel template_type, unsigned int list_length)
{
if (template_type != VALUE_LIST && template_type != COMPLEMENTED_LIST)
TTCN_error("Setting an invalid list for a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
clean_up();
set_selection(template_type);
value_list.n_values = list_length;
value_list.list_value = new Bind_template[list_length];
}

Bind_template& Bind_template::list_item(unsigned int list_index) const
{
if (template_selection != VALUE_LIST && template_selection != COMPLEMENTED_LIST)
TTCN_error("Accessing a list element of a non-list template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
if (list_index >= value_list.n_values)
TTCN_error("Index overflow in a value list template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
return value_list.list_value[list_index];
}

Bind_choice_template& Bind_template::choice()
{
set_specific();
return single_value->field_choice;
}

const Bind_choice_template& Bind_template::choice() const
{
if (template_selection != SPECIFIC_VALUE)
TTCN_error("Accessing field choice of a non-specific template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
return single_value->field_choice;
}

int Bind_template::size_of() const
{
  if (is_ifpresent) TTCN_error("Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind which has an ifpresent attribute.");
  switch (template_selection)
  {
  case SPECIFIC_VALUE:
    return 1;
  case VALUE_LIST:
   {
     if (value_list.n_values<1)
       TTCN_error("Internal error: Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind containing an empty list.");
      int item_size = value_list.list_value[0].size_of();
      for (unsigned int l_idx = 1; l_idx < value_list.n_values; l_idx++)
      {
        if (value_list.list_value[l_idx].size_of()!=item_size)
          TTCN_error("Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind containing a value list with different sizes.");
      }
      return item_size;
    }
  case OMIT_VALUE:
    TTCN_error("Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind containing omit value.");
  case ANY_VALUE:
  case ANY_OR_OMIT:
    TTCN_error("Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind containing */? value.");
  case COMPLEMENTED_LIST:
    TTCN_error("Performing sizeof() operation on a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind containing complemented list.");
  default:
    TTCN_error("Performing sizeof() operation on an uninitialized/unsupported template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
  }
  return 0;
}

void Bind_template::log() const
{
switch (template_selection) {
case SPECIFIC_VALUE:
TTCN_Logger::log_event_str("{ choice := ");
single_value->field_choice.log();
TTCN_Logger::log_event_str(" }");
break;
case COMPLEMENTED_LIST:
TTCN_Logger::log_event_str("complement ");
case VALUE_LIST:
TTCN_Logger::log_char('(');
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++) {
if (list_count > 0) TTCN_Logger::log_event_str(", ");
value_list.list_value[list_count].log();
}
TTCN_Logger::log_char(')');
break;
default:
log_generic();
}
log_ifpresent();
}

void Bind_template::log_match(const Bind& match_value) const
{
if(TTCN_Logger::VERBOSITY_COMPACT == TTCN_Logger::get_matching_verbosity()){
if(match(match_value)){
TTCN_Logger::print_logmatch_buffer();
TTCN_Logger::log_event_str(" matched");
} else{
if (template_selection == SPECIFIC_VALUE) {
size_t previous_size = TTCN_Logger::get_logmatch_buffer_len();
if(!single_value->field_choice.match(match_value.choice())){
TTCN_Logger::log_logmatch_info(".choice");
single_value->field_choice.log_match(match_value.choice());
TTCN_Logger::set_logmatch_buffer_len(previous_size);
}
}else {
TTCN_Logger::print_logmatch_buffer();
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
TTCN_Logger::log_event_str(" unmatched");
}
}
return;
}
if (template_selection == SPECIFIC_VALUE) {
TTCN_Logger::log_event_str("{ choice := ");
single_value->field_choice.log_match(match_value.choice());
TTCN_Logger::log_event_str(" }");
} else {
match_value.log();
TTCN_Logger::log_event_str(" with ");
log();
if (match(match_value)) TTCN_Logger::log_event_str(" matched");
else TTCN_Logger::log_event_str(" unmatched");
}
}

void Bind_template::encode_text(Text_Buf& text_buf) const
{
encode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
single_value->field_choice.encode_text(text_buf);
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
text_buf.push_int(value_list.n_values);
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].encode_text(text_buf);
break;
default:
TTCN_error("Text encoder: Encoding an uninitialized/unsupported template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
}
}

void Bind_template::decode_text(Text_Buf& text_buf)
{
clean_up();
decode_text_base(text_buf);
switch (template_selection) {
case SPECIFIC_VALUE:
single_value = new single_value_struct;
single_value->field_choice.decode_text(text_buf);
case OMIT_VALUE:
case ANY_VALUE:
case ANY_OR_OMIT:
break;
case VALUE_LIST:
case COMPLEMENTED_LIST:
value_list.n_values = text_buf.pull_int().get_val();
value_list.list_value = new Bind_template[value_list.n_values];
for (unsigned int list_count = 0; list_count < value_list.n_values; list_count++)
value_list.list_value[list_count].decode_text(text_buf);
break;
default:
TTCN_error("Text decoder: An unknown/unsupported selection was received in a template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind.");
}
}

void Bind_template::set_param(Module_Param& param)
{
  if (dynamic_cast<Module_Param_Name*>(param.get_id()) != NULL &&
      param.get_id()->next_name()) {
    char* param_field = param.get_id()->get_current_name();
    if (param_field[0] >= '0' && param_field[0] <= '9') {
      param.error("Unexpected array index in module parameter, expected a valid field"
        " name for record template type `@urn_ietf_params_xml_ns_xmpp_bind.Bind'");
    }
    if (strcmp("choice", param_field) == 0) {
      choice().set_param(param);
      return;
    } else param.error("Field `%s' not found in record template type `@urn_ietf_params_xml_ns_xmpp_bind.Bind'", param_field);
  }
  param.basic_check(Module_Param::BC_TEMPLATE, "record template");
  switch (param.get_type()) {
  case Module_Param::MP_Omit:
    *this = OMIT_VALUE;
    break;
  case Module_Param::MP_Any:
    *this = ANY_VALUE;
    break;
  case Module_Param::MP_AnyOrNone:
    *this = ANY_OR_OMIT;
    break;
  case Module_Param::MP_List_Template:
  case Module_Param::MP_ComplementList_Template:
    set_type(param.get_type()==Module_Param::MP_List_Template ? VALUE_LIST : COMPLEMENTED_LIST, param.get_size());
    for (size_t p_i=0; p_i<param.get_size(); p_i++) {
      list_item(p_i).set_param(*param.get_elem(p_i));
    }
    break;
  case Module_Param::MP_Value_List:
    if (1<param.get_size()) {
      param.error("record template of type @urn_ietf_params_xml_ns_xmpp_bind.Bind has 1 fields but list value has %d fields", (int)param.get_size());
    }
    if (param.get_size()>0 && param.get_elem(0)->get_type()!=Module_Param::MP_NotUsed) choice().set_param(*param.get_elem(0));
    break;
  case Module_Param::MP_Assignment_List: {
    Vector<bool> value_used(param.get_size());
    value_used.resize(param.get_size(), false);
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) {
      Module_Param* const curr_param = param.get_elem(val_idx);
      if (!strcmp(curr_param->get_id()->get_name(), "choice")) {
        if (curr_param->get_type()!=Module_Param::MP_NotUsed) {
          choice().set_param(*curr_param);
        }
        value_used[val_idx]=true;
      }
    }
    for (size_t val_idx=0; val_idx<param.get_size(); val_idx++) if (!value_used[val_idx]) {
      param.get_elem(val_idx)->error("Non existent field name in type @urn_ietf_params_xml_ns_xmpp_bind.Bind: %s", param.get_elem(val_idx)->get_id()->get_name());
      break;
    }
  } break;
  default:
    param.type_error("record template", "@urn_ietf_params_xml_ns_xmpp_bind.Bind");
  }
  is_ifpresent = param.get_ifpresent();
}

void Bind_template::check_restriction(template_res t_res, const char* t_name) const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return;
switch ((t_name&&(t_res==TR_VALUE))?TR_OMIT:t_res) {
case TR_OMIT:
if (template_selection==OMIT_VALUE) return;
case TR_VALUE:
if (template_selection!=SPECIFIC_VALUE || is_ifpresent) break;
single_value->field_choice.check_restriction(t_res, t_name ? t_name : "@urn_ietf_params_xml_ns_xmpp_bind.Bind");
return;
case TR_PRESENT:
if (!match_omit()) return;
break;
default:
return;
}
TTCN_error("Restriction `%s' on template of type %s violated.", get_res_name(t_res), t_name ? t_name : "@urn_ietf_params_xml_ns_xmpp_bind.Bind");
}

boolean Bind_template::is_present() const
{
if (template_selection==UNINITIALIZED_TEMPLATE) return FALSE;
return !match_omit();
}

boolean Bind_template::match_omit() const
{
if (is_ifpresent) return TRUE;
switch (template_selection) {
case OMIT_VALUE:
case ANY_OR_OMIT:
return TRUE;
case VALUE_LIST:
case COMPLEMENTED_LIST:
for (unsigned int l_idx=0; l_idx<value_list.n_values; l_idx++)
if (value_list.list_value[l_idx].match_omit())
return template_selection==VALUE_LIST;
return template_selection==COMPLEMENTED_LIST;
default:
return FALSE;
}
return FALSE;
}


/* Bodies of static functions */

static void pre_init_module()
{
XSD::module_object.pre_init_module();
}

static void post_init_module()
{
XSD::module_object.post_init_module();
}


} /* end of namespace */
