// This C++ header file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for user (user@user-multicom) on Fri Oct  9 11:34:10 2015

// Copyright Ericsson Telecom AB 2000-2014

// Do not edit this file unless you know what you are doing.

#ifndef xmpp__connect_HH
#define xmpp__connect_HH

#ifdef TITAN_RUNTIME_2
#error Generated code does not match with used runtime.\
 Code was generated without -R option but -DTITAN_RUNTIME_2 was used.
#endif

/* Header file includes */

#include "XMPP_PortType.hh"

#if TTCN3_VERSION != 50300
#error Version mismatch detected.\
 Please check the version of the TTCN-3 compiler and the base library.
#endif

#ifndef LINUX
#error This file should be compiled on LINUX
#endif

namespace xmpp__connect {

/* Type definitions */

typedef COMPONENT XMPP__TYPE;
typedef COMPONENT_template XMPP__TYPE_template;

/* Function prototypes */

extern verdicttype testcase_SuccessfulConnect(boolean has_timer, double timer_value);

/* Global variable declarations */

extern const TTCN_Typedescriptor_t& XMPP__TYPE_descr_;
extern XMPP__PortType::XMPP__PT XMPP__TYPE_component_XMPP__PORT;
extern TIMER XMPP__TYPE_component_TIMER_;
extern const CHARSTRING& host__name;
extern const INTEGER& port__number;
extern const jabber__client::Message_template& client__message;
extern const http__etherx__jabber__org__streams::Stream_template& client__stream;
extern const http__etherx__jabber__org__streams::Stream_template& server__stream;
extern TTCN_Module module_object;

} /* end of namespace */

#endif
